#!/usr/bin/env python3
# API-quality crawl-gap fix (2026-09, Databricks contest wave): supplements evidence packs with
# verbatim passages from CRAWLED/VERIFIED vendor pages that the LLM extraction passes kept
# missing — same precedent as append-data-warehouses-docs-evidence.py / append-auth-docs-
# evidence.py (per-source extraction caps + limited story quotas starve specific capabilities
# out of the pack even though the corpus contains them verbatim). Context: a fleet audit found
# 54 products with agentic-public-api full/partial but ALL four api-quality stories none/q0;
# live checks confirmed several vendors DO publish machine-readable specs, interactive docs,
# sandboxes, and deprecation policies. Every URL below was added to that product's
# products.json urls.extra, crawled into pipeline/cache/crawl/, and every excerpt quotes the
# crawled page (checked at authoring time, 2026-09-10). Extraction is monotonic and dedups by
# normalized excerpt, so re-running extract after this keeps these items stable.
#
# Verified-honest counterpart (NO items added, on purpose):
#   - databricks api-machine-spec: Databricks publishes NO official OpenAPI download (only an
#     internal _openapi_sha pointer in databricks/cli; community threads confirm) — the
#     existing negative openapi probe stands.
#   - figma api-sandbox: no vendor sandbox/test environment is documented anywhere.
import datetime
import json

NOW = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.000Z')

ITEMS = {
    ('data-warehouses', 'databricks'): [
        ('databricks-supp-api-versioning', 'https://docs.databricks.com/aws/en/sql/dbsql-api-latest',
         'Docs, "Update to the latest Databricks SQL API version": "The legacy API is deprecated and support will end soon. Use this page to migrate your applications and integrations to the new API version" — e.g. "The API path is now api/2.0/sql/queries, replacing the legacy path of /api/2.0/preview/sql/queries".'),
        ('databricks-supp-versioned-apis', 'https://docs.databricks.com/aws/en/reference/api',
         'API reference hub lists versioned REST APIs side by side, e.g. "Jobs v2.0 API — REST API reference for version 2.0 version of the Jobs REST API. Databricks recommends that you use the latest Databricks REST API for new and existing clients and scripts."'),
        ('databricks-supp-api-reference-examples', 'https://docs.databricks.com/api/workspace/introduction',
         'API reference (docs.databricks.com/api): "This reference describes the types, paths, and any request payload or query parameters, for each supported Databricks REST API operation. Many reference pages also provide request and response payload examples. Some reference pages also provide examples for calling a Databricks REST API operation by using the Databricks CLI, the Databricks Terraform provider, or one or more of the Databricks SDKs." (No live try-it runner is documented.)'),
    ],
    ('data-warehouses', 'snowflake'): [
        ('snowflake-supp-openapi-specs', 'https://github.com/snowflakedb/snowflake-rest-api-specs',
         'Official snowflakedb/snowflake-rest-api-specs repo (specifications/ + collections/): "These REST APIs are compliant with the OpenAPI specification. Snowflake REST APIs enable developers and partners to use the language of their choice to build integrations with Snowflake using the openAPI specifications", with importable Postman collections.'),
        ('snowflake-supp-behavior-changes', 'https://docs.snowflake.com/en/release-notes/behavior-changes',
         'Docs, "Behavior change announcements": "To help you manage your operations and minimize disruption to your Snowflake service, we document behavior changes that may impact your usage", organized into dated behavior change bundles plus "Unbundled behavior changes".'),
    ],
    ('code-hosting', 'gitlab'): [
        ('gitlab-supp-openapi-spec', 'https://docs.gitlab.com/api/openapi/',
         'Docs, "OpenAPI": "GitLab documents its REST API using the OpenAPI 3.0 specification (formerly called Swagger)... The OpenAPI spec is autogenerated directly from the API code and is tightly coupled to its implementation, ensuring the documentation is always accurate and up to date"; "The raw OpenAPI 3.0 specification is available in the GitLab monorepo" (doc/api/openapi/openapi_v2.yaml).'),
        ('gitlab-supp-deprecations', 'https://docs.gitlab.com/api/rest/deprecations/',
         'Docs, "REST API deprecations": "You should regularly review the following deprecations and make the recommended changes"; "GitLab will not make these changes within REST API v4, and follows semantic versioning for the REST API" (see /api/rest/#versioning-and-deprecations).'),
    ],
    ('team-chat', 'slack'): [
        ('slack-supp-openapi-spec', 'https://github.com/slackapi/slack-api-specs',
         'Official slackapi/slack-api-specs repo: "This repository contains API specifications of Slack platform features and APIs... You\'ll find OpenAPI specs for the Slack Web API and AsyncAPI specs for the Events API" — Web API OpenAPI 2.0 spec at web-api/slack_web_openapi_v2.json "covers user and bot user token usage of public Web API methods".'),
        ('slack-supp-deprecations', 'https://api.slack.com/changelog/deprecations',
         'api.slack.com/changelog/deprecations is a running, dated log of API deprecation announcements with migration windows, e.g. "We\'d like to update our previous announcement regarding classic app deprecation. We\'re pushing the deprecation date for classic apps to November 16, 2026."'),
    ],
    ('crm', 'hubspot'): [
        ('hubspot-supp-api-versioning', 'https://developers.hubspot.com/docs/api-reference/latest/overview.md',
         'Docs, "2026-09 API reference": "The 2026-09 APIs use a date-based versioning scheme (e.g., /crm/2026-09/)... This versioning model gives HubSpot the ability to ship updates on a predictable schedule. When a new date version is released, the previous version continues to work until its end-of-life date, giving you time to migrate."'),
        ('hubspot-supp-deprecation-policy', 'https://developers.hubspot.com/docs/api-reference/deprecated-apis.md',
         'Docs, "Sunsetted and deprecated APIs": a maintained table of sunsetted APIs with dates and migration targets, plus "Deprecated APIs... HubSpot will continue to support them for the foreseeable future and will announce any future changes with ample notice on HubSpot\'s Developer Changelog."'),
        ('hubspot-supp-openapi-spec', 'https://developers.hubspot.com/docs/api-reference/latest/account/account-information/get-account-details.md',
         'Every endpoint reference page publishes its machine-readable spec inline ("## OpenAPI ... specs/2026-09/account-account-info-v2026-09.json GET /account-info/2026-09/details openapi: 3.0.1"), and the docs are agent-readable: "Fetch the complete documentation index at: https://developers.hubspot.com/docs/llms.txt", "Append .md to any documentation page URL to get its markdown version."'),
    ],
    # 2026-09-14 follow-up: linear was on the same 54-offender audit list as asana but never got
    # the fix — agentic-public-api full yet ALL api-quality stories none/q0. Live checks
    # (curl, this date) confirm every URL below is 200 and every excerpt is verbatim from the
    # crawled .md mirror / repo. Note api-sandbox stays na — Linear documents no developer
    # sandbox environment (verified honest, figma precedent).
    ('project-management', 'linear'): [
        ('linear-supp-graphql-introspection', 'https://linear.app/developers/graphql.md',
         'Docs, "Getting started": "Linear\'s GraphQL endpoint is: https://api.linear.app/graphql — It supports introspection so you can query the whole schema." The full schema SDL is also published in the official linear/linear repo at packages/sdk/src/schema.graphql (kept current by the repo\'s schema GitHub Action).'),
        ('linear-supp-apollo-explorer', 'https://linear.app/developers/graphql.md',
         'Docs, "Getting Started": "Our GraphQL API is explorable and queryable via Apollo Studio (studio.apollographql.com/public/Linear-API), no download or log in required. Click the Schema tab to browse the schema, and click the Explorer tab to run queries."'),
        ('linear-supp-rate-limits', 'https://linear.app/developers/rate-limiting.md',
         'Docs, "Rate limiting" publishes exact per-auth limits ("API key — 2,500 requests per User per 1 hour; OAuth App — 5,000 per User; Unauthenticated — 600 per IP Address"), leaky-bucket refill, complexity limits, and response headers: "X-RateLimit-Requests-Limit — The maximum number of API requests you\'re permitted to make per hour."'),
        ('linear-supp-deprecations', 'https://linear.app/developers/deprecations.md',
         'Docs, "Deprecations": "Linear\'s GraphQL API doesn\'t have versioning like many REST APIs... we take breaking changes and deprecations seriously... If there\'s a noticeable breaking change in the API, we\'ll proactively reach out to developers that use that part of the API and give you plenty of time to make changes... We utilize the @deprecated directive to annotate deprecation warnings in the schema. In addition, changes to the API are listed with [API] prefix in the Linear changelog."'),
    ],
    ('project-management', 'asana'): [
        ('asana-supp-openapi-spec', 'https://github.com/Asana/openapi',
         'Official Asana/openapi repo, "Asana\'s OpenAPI Specifications": "This repository contains the OpenAPI Specification for Asana\'s APIs", publishing the REST API spec (./defs/asana_oas.yaml) and app components spec (./defs/app_components_oas.yaml).'),
        ('asana-supp-deprecations', 'https://developers.asana.com/docs/deprecations',
         'Docs, "Deprecations" ("this page describes our deprecation process"): "We will provide a clear description of the change, how it affects your requests, and a migration plan to follow"; "We will designate a deprecation period during which you will be able to choose between both old and new behavior from the API, allowing you to test out the change without having to put your entire app at risk."'),
    ],
}

for (category, pid), items in ITEMS.items():
    path = f'data/{category}/evidence/{pid}.json'
    ev = json.load(open(path))
    existing = {e['id'] for e in ev}
    appended = 0
    for iid, url, excerpt in items:
        if iid in existing:
            print(f'{category}/{pid}: {iid} already present, skipping')
            continue
        ev.append({'id': iid, 'tier': 'claimed-docs', 'url': url, 'excerpt': excerpt, 'fetchedAt': NOW})
        print(f'{category}/{pid}: appended {iid}')
        appended += 1
    # Only rewrite when something was actually appended, and match the pipeline's writeJson
    # formatting (ensure_ascii=False) — an all-skips rewrite with ASCII-escaped unicode dirties
    # untouched evidence files for zero content change (parsed packs identical, so judge cell
    # hashes are unaffected either way — cellHash hashes parsed excerpts, not file bytes).
    if appended:
        with open(path, 'w') as f:
            f.write(json.dumps(ev, indent=2, ensure_ascii=False) + '\n')
