import fs from 'node:fs'
import path from 'node:path'
import { z } from 'zod'

// Loader for the authored human-step audit (data/human-step-audit.json): one entry per
// non-agent DAG node in the process corpus, generated by pipeline/scripts/audit-human-steps.ts.
// Each entry replaces the three generic gap reasons (lib/gapClosers.ts IRREDUCIBLE_REASON,
// lib/processSim.ts gapWhy) with a per-node root cause and an honest computer-use feasibility
// verdict. Same tolerant-optional contract as lib/processRankings.ts loadStepStoryMap: a
// missing file is an empty audit (renderers fall back to the legacy strings), never an error.

export type ComputerUseFeasibility = 'drivable' | 'assist' | 'policy-gate' | 'no-screen' | 'third-party-wait'

export interface HumanStepAudit {
  taskId: string
  nodeId: string
  route: 'form' | 'person'
  why: string
  computerUse: ComputerUseFeasibility
  computerUseWhy: string
}

const HumanStepAuditSchema = z.object({
  taskId: z.string().min(1),
  nodeId: z.string().min(1),
  route: z.enum(['form', 'person']),
  why: z.string().min(1),
  computerUse: z.enum(['drivable', 'assist', 'policy-gate', 'no-screen', 'third-party-wait']),
  computerUseWhy: z.string().min(1),
})

let cache: HumanStepAudit[] | null = null
let index: Map<string, HumanStepAudit> | null = null

export function loadHumanStepAudit(): HumanStepAudit[] {
  if (cache) return cache
  const file = path.join(process.cwd(), 'data', 'human-step-audit.json')
  cache = fs.existsSync(file)
    ? HumanStepAuditSchema.array().parse(JSON.parse(fs.readFileSync(file, 'utf8')))
    : []
  return cache
}

export function humanStepAudit(taskId: string, nodeId: string): HumanStepAudit | null {
  if (!index) {
    index = new Map(loadHumanStepAudit().map((e) => [`${e.taskId}:${e.nodeId}`, e]))
  }
  return index.get(`${taskId}:${nodeId}`) ?? null
}
