import fs from 'node:fs'
import path from 'node:path'
import { z } from 'zod'
import { resolveGapStep } from './gapClosers'
import { gapWhy, LEGAL_SIGNATURE_WHY } from './processSim'
import type { DagNode, ProcessTask } from './processes'

// Loader for the authored human-step audit (data/human-step-audit.json): one entry per
// non-agent DAG node in the process corpus, generated by pipeline/scripts/audit-human-steps.ts.
// Each entry replaces the three generic gap reasons (lib/gapClosers.ts IRREDUCIBLE_REASON,
// lib/processSim.ts gapWhy) with a per-node root cause and an honest computer-use feasibility
// verdict. Same tolerant-optional contract as lib/processRankings.ts loadStepStoryMap: a
// missing file is an empty audit (renderers fall back to the legacy strings), never an error.

export type ComputerUseFeasibility = 'drivable' | 'assist' | 'policy-gate' | 'no-screen' | 'third-party-wait'

export interface HumanStepAudit {
  taskId: string
  nodeId: string
  route: 'form' | 'person'
  why: string
  computerUse: ComputerUseFeasibility
  computerUseWhy: string
}

const HumanStepAuditSchema = z.object({
  taskId: z.string().min(1),
  nodeId: z.string().min(1),
  route: z.enum(['form', 'person']),
  why: z.string().min(1),
  computerUse: z.enum(['drivable', 'assist', 'policy-gate', 'no-screen', 'third-party-wait']),
  computerUseWhy: z.string().min(1),
})

let cache: HumanStepAudit[] | null = null
let index: Map<string, HumanStepAudit> | null = null

export function loadHumanStepAudit(): HumanStepAudit[] {
  if (cache) return cache
  const file = path.join(process.cwd(), 'data', 'human-step-audit.json')
  cache = fs.existsSync(file)
    ? HumanStepAuditSchema.array().parse(JSON.parse(fs.readFileSync(file, 'utf8')))
    : []
  return cache
}

export function humanStepAudit(taskId: string, nodeId: string): HumanStepAudit | null {
  if (!index) {
    index = new Map(loadHumanStepAudit().map((e) => [`${e.taskId}:${e.nodeId}`, e]))
  }
  return index.get(`${taskId}:${nodeId}`) ?? null
}

// ---------------------------------------------------------------------------
// Verdict-box bucketing (components/ProcessVerdict.tsx renders exactly these buckets)
// ---------------------------------------------------------------------------

// One non-agent step with node identity + its authored audit — the row shape every verdict
// bucket shares.
export interface VerdictGap {
  taskId: string
  node: DagNode
  audit: HumanStepAudit | null
  // The honest one-liner for the bucket: the closer blurb, the irreducible reason, or the
  // generic gap phrase.
  why: string
}

export interface VerdictGaps {
  // Legally-required human signature/attestation acts (DagNode.legalSignature) — the founder's
  // true human floor (2026-09-21). Checked FIRST: a signature step never gets a workaround or
  // computer-use chips, whatever the keyword rules would have said about its label.
  signature: VerdictGap[]
  closable: VerdictGap[]
  irreducible: VerdictGap[]
  unclosed: VerdictGap[]
  // Distinct arena names backing the closable gaps, in first-seen order.
  arenas: string[]
}

export function verdictGaps(tasks: ProcessTask[], dir?: string): VerdictGaps {
  const out: VerdictGaps = { signature: [], closable: [], irreducible: [], unclosed: [], arenas: [] }
  for (const task of tasks) {
    for (const node of task.dag.nodes) {
      if (node.route === 'agent') continue
      const audit = humanStepAudit(task.id, node.id)
      const row = { taskId: task.id, node, audit }
      if (node.legalSignature) {
        out.signature.push({ ...row, why: LEGAL_SIGNATURE_WHY })
        continue
      }
      const res = resolveGapStep(node, dir)
      if (res?.kind === 'closer') {
        out.closable.push({ ...row, why: res.closer.blurb })
        if (!out.arenas.includes(res.closer.arenaName)) out.arenas.push(res.closer.arenaName)
      } else if (res?.kind === 'irreducible') {
        out.irreducible.push({ ...row, why: res.reason })
      } else {
        out.unclosed.push({ ...row, why: gapWhy(node.route) })
      }
    }
  }
  return out
}
