import fs from 'node:fs'
import path from 'node:path'

// Which recorded proofs can ALSO be re-run live — the committed manifest behind the "Try it"
// microterminal's "run live" button. Generated by
// pipeline/scripts/generate-live-probe-manifest.ts (data/live-probes.json, mirrored into the
// worker as infra/cloudflare-proxy/live-probes.generated.js — the worker copy is the one that
// executes; this loader only decides which stories get the button). Server-only (fs reads at
// build time — the site is a static export).

interface LiveProbeManifest {
  probes: Array<{ arena: string; productId: string; probeId: string }>
}

const DEFAULT_DIR = () => path.join(process.cwd(), 'data')

let defaultCache: Set<string> | null = null

function loadKeys(dir: string): Set<string> {
  const file = path.join(dir, 'live-probes.json')
  if (!fs.existsSync(file)) return new Set()
  const manifest = JSON.parse(fs.readFileSync(file, 'utf8')) as LiveProbeManifest
  return new Set(manifest.probes.map((p) => `${p.arena}/${p.productId}/${p.probeId}`))
}

// True when this (arena, product, probe) recording has a live-capable manifest entry — i.e. the
// worker can re-run its exact command as a fetch. Missing manifest = nothing is live (honest
// degrade, never an error).
export function isLiveCapable(category: string, productId: string, probeId: string, dir?: string): boolean {
  if (dir) return loadKeys(dir).has(`${category}/${productId}/${probeId}`)
  if (!defaultCache) defaultCache = loadKeys(DEFAULT_DIR())
  return defaultCache.has(`${category}/${productId}/${probeId}`)
}
