// GENERATED by scripts/generate-mcp-allowlist.mjs — do not edit by hand; re-run the script
// after data changes. Maps "arena/productId" to that product's OWN documented remote MCP
// endpoint (scanned from committed data with a vendor-domain guard — see the script header).
// The identical map is hardcoded as MCP_ENDPOINTS in infra/cloudflare-proxy/worker.js (kept
// dependency-free on purpose); a unit test asserts the two never drift.
export const MCP_ENDPOINTS: Record<string, string> = {
  'accounting/xero': 'https://mcp.xero.com/mcp',
  'api-platforms/postman': 'https://mcp.postman.com/mcp',
  'backend-as-a-service/supabase': 'https://mcp.supabase.com/mcp',
  'mobile-payments/sumup': 'https://mcp.sumup.com/mcp',
  'payments/paypal': 'https://mcp.paypal.com/mcp',
  'payments/stripe': 'https://mcp.stripe.com/',
  'startup-banking/mercury': 'https://mcp.mercury.com/mcp',
  'web-scraping/scrapingbee': 'https://mcp.scrapingbee.com/',
}

export function mcpEndpointFor(category: string, productId: string): string | null {
  return MCP_ENDPOINTS[`${category}/${productId}`] ?? null
}
