// GENERATED by scripts/generate-mcp-allowlist.mjs — do not edit by hand; re-run the script
// after data changes. Maps "arena/productId" to that product's OWN documented remote MCP
// endpoint (scanned from committed data with a vendor-domain guard — see the script header).
// The identical map is hardcoded as MCP_ENDPOINTS in infra/cloudflare-proxy/worker.js (kept
// dependency-free on purpose); a unit test asserts the two never drift.
export const MCP_ENDPOINTS: Record<string, string> = {
  'accounting/xero': 'https://mcp.xero.com/mcp',
  'ai-memory/mem0': 'https://mcp.mem0.ai/mcp',
  'ai-memory/supermemory': 'https://mcp.supermemory.ai/mcp',
  'ai-research-agents/undermind': 'https://mcp.undermind.ai/mcp',
  'api-platforms/postman': 'https://mcp.postman.com/mcp',
  'auth-platforms/better-auth': 'https://mcp.better-auth.com/mcp',
  'auth-platforms/workos': 'https://mcp.workos.com/mcp',
  'backend-as-a-service/supabase': 'https://mcp.supabase.com/mcp',
  'customer-data-platforms/rudderstack': 'https://mcp.rudderstack.com/mcp',
  'design-tools/canva': 'https://mcp.canva.com/mcp',
  'design-tools/figma': 'https://mcp.figma.com/mcp',
  'email/missive': 'https://mcp.missiveapp.com/',
  'feature-flags/flagsmith': 'https://mcp.flagsmith.com/',
  'incident-management/incident-io': 'https://mcp.incident.io/mcp',
  'incident-management/pagerduty': 'https://mcp.pagerduty.com/mcp',
  'incident-management/rootly': 'https://mcp.rootly.com/mcp',
  'meeting-ai/granola': 'https://mcp.granola.ai/mcp',
  'meeting-ai/otter': 'https://mcp.otter.ai/mcp',
  'mobile-payments/sumup': 'https://mcp.sumup.com/mcp',
  'observability/honeycomb': 'https://mcp.honeycomb.io/mcp',
  'observability/new-relic': 'https://mcp.newrelic.com/mcp',
  'observability/sentry': 'https://mcp.sentry.dev/mcp',
  'payments/paypal': 'https://mcp.paypal.com/mcp',
  'payments/stripe': 'https://mcp.stripe.com/',
  'scheduling/cal-com': 'https://mcp.cal.com/mcp',
  'scheduling/calendly': 'https://mcp.calendly.com/',
  'scheduling/reclaim': 'https://mcp.reclaim.ai/',
  'search-infra/algolia': 'https://mcp.algolia.com/mcp',
  'serverless-databases/neon': 'https://mcp.neon.tech/mcp',
  'startup-banking/mercury': 'https://mcp.mercury.com/mcp',
  'voice-agents/retell': 'https://mcp.retellai.com/',
  'voice-agents/vapi': 'https://mcp.vapi.ai/mcp',
  'web-scraping/scrapingbee': 'https://mcp.scrapingbee.com/',
  'workflow-automation/make': 'https://mcp.make.com/',
}

export function mcpEndpointFor(category: string, productId: string): string | null {
  return MCP_ENDPOINTS[`${category}/${productId}`] ?? null
}
