import fs from 'node:fs'
import path from 'node:path'
import { z } from 'zod'

// Loader for the committed step→prompt file (data/step-prompts.json): one copy-pasteable
// prompt per (task, DAG node) that a reader can hand to their own agent (Claude, etc.) to
// perform that step, generated by pipeline/scripts/map-step-prompts.ts — grounded in the
// step's mapped stories, grounded vendor calls, and human-step audit, with the literal
// `{{vendor}}` placeholder where the renderer substitutes the reader's stack pick or the
// step's top vendor. Same tolerant-optional contract as lib/humanSteps.ts: a missing file is
// an empty list (no prompt panels anywhere), never an error. Display-only, never feeds
// scoring.

export interface StepPrompt { taskId: string; nodeId: string; prompt: string }

const StepPromptSchema = z.object({
  taskId: z.string().min(1),
  nodeId: z.string().min(1),
  prompt: z.string().min(1),
})

let cache: StepPrompt[] | null = null
let index: Map<string, StepPrompt> | null = null

export function loadStepPrompts(): StepPrompt[] {
  if (cache) return cache
  const file = path.join(process.cwd(), 'data', 'step-prompts.json')
  cache = fs.existsSync(file)
    ? StepPromptSchema.array().parse(JSON.parse(fs.readFileSync(file, 'utf8')))
    : []
  return cache
}

export function stepPromptFor(taskId: string, nodeId: string): StepPrompt | null {
  if (!index) {
    index = new Map(loadStepPrompts().map((e) => [`${e.taskId}:${e.nodeId}`, e]))
  }
  return index.get(`${taskId}:${nodeId}`) ?? null
}
