import path from 'node:path'
import { isPopulated, loadCategory } from './data'
import { processIcon } from './processIcons'
import { loadStepStoryMap, STEP_STORY_KINDS, type StepStoryEntry } from './processRankings'
import { loadProcesses, processSlug, type ProcessTask } from './processes'
import type { StoryProcessLink } from './storyVerdictsSort'

// The story↔process connection layer — founder ask (2026-09-22): "map all the connections
// between user stories and the Processes; add a column to the user story table that finds the
// matching processes it relates to. This connection between stories and processes should form
// a large DAG on our backend."
//
// Two surfaces, ONE source of truth — the SAME committed mapping the process pages rank from
// (data/process-step-stories.json, generated by pipeline/scripts/map-step-stories.ts):
//
//   processesForStory / storyProcessesForArena — the reverse of lib/processRankings.ts's
//     step→stories direction (and the story-side sibling of lib/vendorProcesses.ts): given one
//     arena story, which processes (and which of their steps, by which mapping kind) relate to
//     it. Powers the "Processes" column on the product page's story-verdicts table.
//
//   buildStoryGraph — the full backend DAG connecting the whole corpus:
//     process (task:<id>) → step (step:<taskId>:<nodeId>)        dag membership
//     step → story (story:<arenaId>:<storyId>)                   the committed mapping, kind-tagged
//     story → product (product:<arenaId>:<productId>)            judged full/partial verdicts only
//     Exported as a public artifact (data/graph.json via pipeline/scripts/generate-story-graph.ts,
//     mirrored to /productarena/data/graph.json by scripts/copy-data.mjs like every data file).
//
// Everything here is DERIVATION over already-judged data — display/export only, never feeds
// scoring, never writes; same contract as lib/processRankings.ts and lib/vendorProcesses.ts.
// Deterministic by construction: corpus order → DAG node order → kind order (STEP_STORY_KINDS)
// → arena id → the mapping file's own storyId order → each arena's products.json order.

export type StoryProcessKind = StepStoryEntry['kind']

// One (process, step) a story relates to, via one committed mapping entry.
export interface StoryProcessAppearance {
  taskId: string
  slug: string
  title: string
  icon: string
  nodeId: string
  nodeLabel: string
  kind: StoryProcessKind
}

const DEFAULT_DIR = () => path.join(process.cwd(), 'data')

const kindRank = (k: StoryProcessKind) => (STEP_STORY_KINDS as readonly string[]).indexOf(k)

// The mapping grouped per step, in deterministic per-step order (kind, then arena) — the shared
// iteration both the reverse index and the graph build walk, so the two can never disagree.
function entriesByStep(dir: string): Map<string, StepStoryEntry[]> {
  const byStep = new Map<string, StepStoryEntry[]>()
  for (const e of loadStepStoryMap(dir)) {
    const key = `${e.taskId}:${e.nodeId}`
    const list = byStep.get(key) ?? []
    list.push(e)
    byStep.set(key, list)
  }
  for (const list of byStep.values()) {
    list.sort((a, b) => kindRank(a.kind) - kindRank(b.kind) || a.arenaId.localeCompare(b.arenaId))
  }
  return byStep
}

// ---------------------------------------------------------------------------
// The reverse index: story → processes
// ---------------------------------------------------------------------------

// `${arenaId}:${storyId}` → appearances, in corpus order (task, then DAG node, then kind).
const reverseCache = new Map<string, Map<string, StoryProcessAppearance[]>>()

function reverseIndex(dir: string): Map<string, StoryProcessAppearance[]> {
  const hit = reverseCache.get(dir)
  if (hit) return hit
  const byStep = entriesByStep(dir)
  const index = new Map<string, StoryProcessAppearance[]>()
  for (const task of loadProcesses(dir)) {
    const slug = processSlug(task.title)
    const icon = processIcon(task.id)
    for (const node of task.dag.nodes) {
      for (const entry of byStep.get(`${task.id}:${node.id}`) ?? []) {
        for (const storyId of entry.storyIds) {
          const key = `${entry.arenaId}:${storyId}`
          const list = index.get(key) ?? []
          list.push({
            taskId: task.id, slug, title: task.title, icon,
            nodeId: node.id, nodeLabel: node.label, kind: entry.kind,
          })
          index.set(key, list)
        }
      }
    }
  }
  reverseCache.set(dir, index)
  return index
}

// Every (process, step) one arena story relates to via the committed step→stories mapping —
// corpus order, deterministic. Stories no mapping entry references return [] (most stories:
// the mapping is per-step relevance, not total coverage) and render nothing.
export function processesForStory(
  arenaId: string,
  storyId: string,
  dir: string = DEFAULT_DIR(),
): StoryProcessAppearance[] {
  return reverseIndex(dir).get(`${arenaId}:${storyId}`) ?? []
}

// The lean serialized shape the story-verdicts table's "Processes" column needs: for one arena,
// storyId → distinct related processes (deduped by task, first appearance order — a story
// mapped onto three steps of "Run payroll" is still ONE chip). Only stories with ≥1 process
// get a key, so `rec[storyId] ?? []` is the honest per-row read.
export function storyProcessesForArena(
  arenaId: string,
  dir: string = DEFAULT_DIR(),
): Record<string, StoryProcessLink[]> {
  const out: Record<string, StoryProcessLink[]> = {}
  const prefix = `${arenaId}:`
  for (const [key, appearances] of reverseIndex(dir)) {
    if (!key.startsWith(prefix)) continue
    const storyId = key.slice(prefix.length)
    const seen = new Set<string>()
    const links: StoryProcessLink[] = []
    for (const a of appearances) {
      if (seen.has(a.taskId)) continue
      seen.add(a.taskId)
      links.push({ slug: a.slug, title: a.title, icon: a.icon })
    }
    if (links.length > 0) out[storyId] = links
  }
  return out
}

// ---------------------------------------------------------------------------
// The full backend DAG
// ---------------------------------------------------------------------------

export type StoryProcessGraphNodeType = 'process' | 'step' | 'story' | 'product'

export interface StoryProcessGraphNode {
  id: string
  type: StoryProcessGraphNodeType
  label: string
}

export type StoryProcessGraphEdgeType = 'has-step' | 'step-story' | 'story-product'

export interface StoryProcessGraphEdge {
  from: string
  to: string
  type: StoryProcessGraphEdgeType
  // step-story edges carry the mapping kind (function / computer-use / extra).
  kind?: StoryProcessKind
  // story-product edges carry the judged verdict (full / partial only — a "serves it" claim
  // needs judged coverage; none/disputed/na cells are honestly absent from the graph).
  verdict?: 'full' | 'partial'
}

export interface StoryProcessGraph {
  nodes: StoryProcessGraphNode[]
  edges: StoryProcessGraphEdge[]
  counts: {
    nodes: Record<StoryProcessGraphNodeType, number>
    edges: Record<StoryProcessGraphEdgeType, number>
  }
}

export const processNodeId = (taskId: string) => `task:${taskId}`
export const stepNodeId = (taskId: string, nodeId: string) => `step:${taskId}:${nodeId}`
export const storyNodeId = (arenaId: string, storyId: string) => `story:${arenaId}:${storyId}`
export const productNodeId = (arenaId: string, productId: string) => `product:${arenaId}:${productId}`

const graphCache = new Map<string, StoryProcessGraph>()

// The whole connection DAG, deterministic (double-builds are byte-identical). Arena data is
// read LAZILY: only arenas the committed mapping actually references are loaded, and only for
// their referenced stories. Mapping entries pointing at tasks/steps no longer in the corpus,
// unpopulated arenas, or story ids the arena no longer carries are skipped — a stale mapping
// never produces a dangling edge (and the tests forbid the corpus-side staleness anyway).
export function buildStoryGraph(dir: string = DEFAULT_DIR()): StoryProcessGraph {
  const hit = graphCache.get(dir)
  if (hit) return hit

  const tasks: ProcessTask[] = loadProcesses(dir)
  const byStep = entriesByStep(dir)
  const nodes: StoryProcessGraphNode[] = []
  const edges: StoryProcessGraphEdge[] = []
  const nodeIds = new Set<string>()
  const addNode = (node: StoryProcessGraphNode) => {
    if (nodeIds.has(node.id)) return
    nodeIds.add(node.id)
    nodes.push(node)
  }

  // Pass 1 — processes, steps (dag membership), and step→story edges, in corpus order.
  // Story nodes enter in first-referenced order.
  const storyRefs: Array<{ arenaId: string; storyId: string }> = []
  for (const task of tasks) {
    const taskNode = processNodeId(task.id)
    addNode({ id: taskNode, type: 'process', label: task.title })
    for (const node of task.dag.nodes) {
      const stepNode = stepNodeId(task.id, node.id)
      addNode({ id: stepNode, type: 'step', label: node.label })
      edges.push({ from: taskNode, to: stepNode, type: 'has-step' })
      for (const entry of byStep.get(`${task.id}:${node.id}`) ?? []) {
        if (!isPopulated(entry.arenaId, dir)) continue
        const lookup = loadCategory(entry.arenaId, dir)
        const known = new Set(lookup.stories.map((s) => s.id))
        for (const storyId of entry.storyIds) {
          if (!known.has(storyId)) continue // stale mapping never dangles
          const storyNode = storyNodeId(entry.arenaId, storyId)
          if (!nodeIds.has(storyNode)) {
            addNode({
              id: storyNode,
              type: 'story',
              label: lookup.stories.find((s) => s.id === storyId)!.title,
            })
            storyRefs.push({ arenaId: entry.arenaId, storyId })
          }
          edges.push({ from: stepNode, to: storyNode, type: 'step-story', kind: entry.kind })
        }
      }
    }
  }

  // Pass 2 — story→product edges: every judged full/partial verdict on a referenced story,
  // in story-node order × the arena's products.json order. Product nodes enter on first edge.
  for (const { arenaId, storyId } of storyRefs) {
    const lookup = loadCategory(arenaId, dir)
    const verdictOf = new Map(lookup.verdicts.filter((v) => v.storyId === storyId).map((v) => [v.productId, v]))
    for (const product of lookup.products) {
      const v = verdictOf.get(product.id)
      if (!v || (v.verdict !== 'full' && v.verdict !== 'partial')) continue
      const productNode = productNodeId(arenaId, product.id)
      addNode({ id: productNode, type: 'product', label: product.name })
      edges.push({
        from: storyNodeId(arenaId, storyId),
        to: productNode,
        type: 'story-product',
        verdict: v.verdict,
      })
    }
  }

  const counts: StoryProcessGraph['counts'] = {
    nodes: { process: 0, step: 0, story: 0, product: 0 },
    edges: { 'has-step': 0, 'step-story': 0, 'story-product': 0 },
  }
  for (const n of nodes) counts.nodes[n.type] += 1
  for (const e of edges) counts.edges[e.type] += 1

  const graph: StoryProcessGraph = { nodes, edges, counts }
  graphCache.set(dir, graph)
  return graph
}
