// The derived-vs-curated timeline report (founder depth wave part 2, 2026-10-01): compare the
// dependency graph's derived ordering (lib/processDeps.ts) against the curated `timeOrder`
// founder timeline and COMMIT the result as docs/TIMELINE-INVERSIONS.md, so the worklist can't
// go stale silently — the drift test (lib/__tests__/processDeps.test.ts) fails whenever the
// committed report diverges from what the live corpus generates. Report, never auto-fix:
// renumbering timeOrder is the founder's curation act, not this script's.
// Regenerate with: npx tsx scripts/generate-timeline-inversions.ts
import fs from 'node:fs'
import path from 'node:path'
import { placementSlack, timelineInversions } from '../lib/processDeps'
import { loadProcesses } from '../lib/processes'

const ROOT = path.resolve(__dirname, '..')
export const TIMELINE_INVERSIONS_FILE = path.join(ROOT, 'docs', 'TIMELINE-INVERSIONS.md')

// Deterministic: built only from the committed corpus + registry (no dates, no environment
// reads), so regenerating on an unchanged corpus is byte-identical.
export function timelineInversionsMarkdown(): string {
  const inversions = timelineInversions()
  const slack = placementSlack()
  const total = loadProcesses().length
  const lines: string[] = []
  lines.push('# Timeline inversions — the founder renumbering worklist')
  lines.push('')
  lines.push(
    'GENERATED by `scripts/generate-timeline-inversions.ts` from the typed artifact layer ' +
      '(`processes/artifacts.json` + each process’s `produces`/`requires`) — edit the corpus, ' +
      'never this file; the drift test in `lib/__tests__/processDeps.test.ts` pins it to the live data.',
  )
  lines.push('')
  lines.push(
    `Every place the curated \`timeOrder\` founder timeline (${total} processes) orders a ` +
      'CONSUMER before its artifact’s canonical producer. These are reported, not auto-fixed: ' +
      'each row is either a timeline position to renumber or an honest corpus finding (the first ' +
      'hire’s option grant really does presuppose a 409A the timeline places later). Deciding ' +
      'which is the founder’s call.',
  )
  lines.push('')
  lines.push(`## Inversions (${inversions.length})`)
  lines.push('')
  lines.push('| # | Consumer (curated position) | needs | Producer (curated position) |')
  lines.push('|---|---|---|---|')
  inversions.forEach((inv, i) => {
    lines.push(
      `| ${i + 1} | ${inv.consumerTitle} \`${inv.consumerId}\` (#${inv.consumerTimeOrder}) ` +
        `| ${inv.artifactLabel} \`${inv.artifactId}\` ` +
        `| ${inv.producerTitle} \`${inv.producerId}\` (#${inv.producerTimeOrder}) |`,
    )
  })
  lines.push('')
  lines.push('## Placement slack (curated position ≥40 slots later than dependencies force)')
  lines.push('')
  lines.push(
    'The complement question: processes the curated timeline places far LATER than their typed ' +
      'dependencies require. Big slack is a placement QUESTION, not an error — top of the list, ' +
      '“Apply to Y Combinator” sits at the very end of the curated timeline while its only ' +
      'typed need (the founder agreement) exists by position 4.',
  )
  lines.push('')
  lines.push('| Process | curated | earliest feasible | slack |')
  lines.push('|---|---|---|---|')
  for (const s of slack) {
    lines.push(`| ${s.title} \`${s.id}\` | #${s.curatedTimeOrder} | #${s.earliestFeasible} | ${s.slack} |`)
  }
  lines.push('')
  return lines.join('\n')
}

function main(): void {
  fs.writeFileSync(TIMELINE_INVERSIONS_FILE, timelineInversionsMarkdown())
  console.log(`wrote ${path.relative(ROOT, TIMELINE_INVERSIONS_FILE)}`)
}

if (require.main === module) main()
