import { MCP_INITIALIZE, type LocalProbe } from './types'

export const probes: LocalProbe[] = [
    {
      probeId: 'cli-version',
      productId: 'claude-code',
      storyIds: ['agentic-official-cli'],
      bin: 'claude',
      argv: ['claude', '--version'],
      displayCommand: 'claude --version',
      expect: /\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-serve-handshake',
      productId: 'claude-code',
      storyIds: ['agentic-mcp-server'],
      bin: 'claude',
      argv: ['claude', 'mcp', 'serve'],
      displayCommand: `echo '<jsonrpc initialize>' | claude mcp serve`,
      stdinPayload: MCP_INITIALIZE,
      expect: /"serverInfo"/,
      longRunning: true,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'codex',
      storyIds: ['agentic-official-cli'],
      bin: 'codex',
      argv: ['codex', '--version'],
      displayCommand: 'codex --version',
      expect: /codex-cli \d/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-server-handshake',
      productId: 'codex',
      storyIds: ['agentic-mcp-server'],
      bin: 'codex',
      argv: ['codex', 'mcp-server'],
      displayCommand: `echo '<jsonrpc initialize>' | codex mcp-server`,
      stdinPayload: MCP_INITIALIZE,
      expect: /"serverInfo"/,
      longRunning: true,
      timeoutMs: 30_000,
    },
    {
      probeId: 'exec-headless-help',
      productId: 'codex',
      storyIds: ['agentic-headless'],
      bin: 'codex',
      argv: ['codex', 'exec', '--help'],
      displayCommand: 'codex exec --help',
      expect: /non-interactively/i,
      timeoutMs: 30_000,
    },
]
