import { CURL_MCP_INIT, type LocalProbe } from './types'

// Banking-as-a-service: the post-Synapse arena where machine-readable trust is the product.
// llms.txt is live on every vendor's docs host (recorded on all six), and four of six publish
// raw OpenAPI specs at stable URLs — Column's 3.0 YAML (792KB, generated by columnctl),
// Increase's undocumented-but-live /openapi.json, Synctera's openapi-v2.json, and Treasury
// Prime's domain-split specs. Every core banking API answers keyless with a clean JSON 401
// (Stripe Treasury's canonical platform 401, Increase, Column, Unit's JSON:API 401, Synctera)
// EXCEPT Treasury Prime, whose edge answers a keyless request with a WAF-style
// 403 "Access denied" instead of an auth challenge — recorded as-is; the difference is the
// finding. Stripe is the only vendor with any MCP server (OAuth-gated platform MCP); no
// dedicated banking MCP exists anywhere in the arena — the absence is the other finding. All
// probes are keyless, read-only curls.
export const probes: LocalProbe[] = [
  {
    // Treasury's core object — financial accounts — answers a keyless request with Stripe's
    // canonical 401 challenge.
    probeId: 'api-auth-challenge',
    productId: 'stripe-treasury',
    storyIds: ['account-opening-api', 'agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -si --max-time 20 https://api.stripe.com/v1/treasury/financial_accounts | head -4'],
    displayCommand: 'curl -si https://api.stripe.com/v1/treasury/financial_accounts | head -4  # Treasury financial-accounts API, keyless → 401',
    expect: /401/,
    timeoutMs: 30_000,
  },
  {
    // Stripe's documented remote MCP server answers a keyless initialize with its OAuth
    // protected-resource challenge — Treasury objects ride the same platform surface. The
    // only MCP server in the whole BaaS arena.
    probeId: 'mcp-authgate',
    productId: 'stripe-treasury',
    storyIds: ['agentic-mcp-server', 'agent-reads-banking-state'],
    bin: 'curl',
    argv: [
      'sh', '-c',
      `curl -si --max-time 20 -X POST https://mcp.stripe.com/ -H 'Content-Type: application/json' -H 'Accept: application/json, text/event-stream' -d '${CURL_MCP_INIT.replace(/'/g, `'\\''`)}' | grep -i 'HTTP/\\|www-authenticate'`,
    ],
    displayCommand: `curl -si -X POST https://mcp.stripe.com/ -H 'Content-Type: application/json' -d '<jsonrpc initialize>'  # the remote MCP server Stripe documents at docs.stripe.com/mcp`,
    expect: /oauth-protected-resource/,
    timeoutMs: 30_000,
  },
  {
    // docs.stripe.com serves llms.txt (which explicitly routes agents to the v2 "Treasury for
    // Platforms" docs over the legacy v1 API).
    probeId: 'docs-llms-txt',
    productId: 'stripe-treasury',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://docs.stripe.com/llms.txt | head -3'],
    displayCommand: 'curl -sL https://docs.stripe.com/llms.txt | head -3',
    expect: /# Stripe Documentation/,
    timeoutMs: 30_000,
  },
  {
    // Unit's sandbox API answers a keyless request with a clean JSON:API 401.
    probeId: 'api-auth-challenge',
    productId: 'unit',
    storyIds: ['account-opening-api', 'agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -si --max-time 20 https://api.s.unit.sh/accounts | head -3'],
    displayCommand: 'curl -si https://api.s.unit.sh/accounts | head -3  # keyless → 401 (application/vnd.api+json)',
    expect: /401/,
    timeoutMs: 30_000,
  },
  {
    // unit.co serves llms.txt — written for LLMs down to branding guidance, and naming
    // "automated and agent-driven financial workflows" as a use case.
    probeId: 'site-llms-txt',
    productId: 'unit',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://www.unit.co/llms.txt | head -3'],
    displayCommand: 'curl -sL https://www.unit.co/llms.txt | head -3',
    expect: /# Unit/,
    timeoutMs: 30_000,
  },
  {
    // Increase's accounts API answers a keyless request with a clean JSON 401.
    probeId: 'api-auth-challenge',
    productId: 'increase',
    storyIds: ['account-opening-api', 'agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -si --max-time 20 https://api.increase.com/accounts | head -3'],
    displayCommand: 'curl -si https://api.increase.com/accounts | head -3  # keyless → 401',
    expect: /401/,
    timeoutMs: 30_000,
  },
  {
    // Increase publishes its full OpenAPI spec at a stable URL (4.2MB, live even though the
    // docs don't advertise it).
    probeId: 'openapi-spec',
    productId: 'increase',
    storyIds: ['agentic-public-api', 'api-machine-spec'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -s --max-time 20 https://increase.com/openapi.json | head -c 120'],
    displayCommand: 'curl -s https://increase.com/openapi.json | head -c 120',
    expect: /components|openapi/,
    timeoutMs: 30_000,
  },
  {
    // increase.com serves llms.txt (with .md-twin instructions for every documentation page).
    probeId: 'site-llms-txt',
    productId: 'increase',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://increase.com/llms.txt | head -3'],
    displayCommand: 'curl -sL https://increase.com/llms.txt | head -3',
    expect: /# Increase/,
    timeoutMs: 30_000,
  },
  {
    // Column's bank-accounts API answers a keyless request with a clean 401 — a nationally
    // chartered bank whose API edge speaks plain JSON.
    probeId: 'api-auth-challenge',
    productId: 'column',
    storyIds: ['account-opening-api', 'agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -si --max-time 20 https://api.column.com/bank-accounts | head -3'],
    displayCommand: 'curl -si https://api.column.com/bank-accounts | head -3  # keyless → 401',
    expect: /401/,
    timeoutMs: 30_000,
  },
  {
    // Column publishes its OpenAPI 3.0 spec (792KB YAML, auto-generated by columnctl) at a
    // stable URL, alongside a 1.24MB llms-full.txt.
    probeId: 'openapi-spec',
    productId: 'column',
    storyIds: ['agentic-public-api', 'api-machine-spec'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -s --max-time 20 https://docs.column.com/openapi.yaml | head -4'],
    displayCommand: 'curl -s https://docs.column.com/openapi.yaml | head -4',
    expect: /openapi: 3\.0/,
    timeoutMs: 30_000,
  },
  {
    // docs.column.com serves llms.txt (the marketing root does too).
    probeId: 'docs-llms-txt',
    productId: 'column',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://column.com/llms.txt | head -3'],
    displayCommand: 'curl -sL https://column.com/llms.txt | head -3',
    expect: /# Column/,
    timeoutMs: 30_000,
  },
  {
    // Synctera's v0 API answers a keyless request with a clean JSON 401.
    probeId: 'api-auth-challenge',
    productId: 'synctera',
    storyIds: ['account-opening-api', 'agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -si --max-time 20 https://api.synctera.com/v0/accounts | head -3'],
    displayCommand: 'curl -si https://api.synctera.com/v0/accounts | head -3  # keyless → 401',
    expect: /401/,
    timeoutMs: 30_000,
  },
  {
    // Synctera publishes its raw OpenAPI v2 spec at a stable URL.
    probeId: 'openapi-spec',
    productId: 'synctera',
    storyIds: ['agentic-public-api', 'api-machine-spec'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -s --max-time 20 https://docs.synctera.com/openapi-v2.json | head -c 120'],
    displayCommand: 'curl -s https://docs.synctera.com/openapi-v2.json | head -c 120',
    expect: /components|openapi/,
    timeoutMs: 30_000,
  },
  {
    // docs.synctera.com serves llms.txt with recursive _llms markdown indexes (658 pages).
    probeId: 'docs-llms-txt',
    productId: 'synctera',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://docs.synctera.com/llms.txt | head -3'],
    displayCommand: 'curl -sL https://docs.synctera.com/llms.txt | head -3',
    expect: /# Synctera/,
    timeoutMs: 30_000,
  },
  {
    // Treasury Prime's API edge answers a keyless request with a WAF-style 403 "Access
    // denied" — not a clean auth challenge like every other vendor here. Recorded as-is;
    // the difference is the finding.
    probeId: 'api-keyless-response',
    productId: 'treasury-prime',
    storyIds: ['agentic-public-api'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -s --max-time 20 https://api.treasuryprime.com/account | head -c 120'],
    displayCommand: 'curl -s https://api.treasuryprime.com/account | head -c 120  # keyless → 403 "Access denied", not an auth challenge',
    expect: /Access denied/,
    timeoutMs: 30_000,
  },
  {
    // Treasury Prime publishes domain-split OpenAPI specs (payments, account, apply, cards,
    // testing, utilities) at stable URLs.
    probeId: 'openapi-spec',
    productId: 'treasury-prime',
    storyIds: ['agentic-public-api', 'api-machine-spec'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -s --max-time 20 https://docs.treasuryprime.com/api-reference/openapi-payments.json | head -c 120'],
    displayCommand: 'curl -s https://docs.treasuryprime.com/api-reference/openapi-payments.json | head -c 120',
    expect: /components|openapi/,
    timeoutMs: 30_000,
  },
  {
    // docs.treasuryprime.com serves llms.txt (42KB full page index with .md links).
    probeId: 'docs-llms-txt',
    productId: 'treasury-prime',
    storyIds: ['agentic-agent-docs'],
    bin: 'curl',
    argv: ['sh', '-c', 'curl -sL --max-time 20 https://docs.treasuryprime.com/llms.txt | head -3'],
    displayCommand: 'curl -sL https://docs.treasuryprime.com/llms.txt | head -3',
    expect: /Treasury Prime/i,
    timeoutMs: 30_000,
  },
]
