import type { LocalProbe } from './types'

export const probes: LocalProbe[] = [
    {
      probeId: 'cli-version',
      productId: 'terraform',
      storyIds: ['agentic-official-cli'],
      bin: 'terraform',
      argv: ['terraform', 'version'],
      displayCommand: 'terraform version',
      expect: /Terraform v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'plan-headless-help',
      productId: 'terraform',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'terraform',
      argv: ['terraform', 'plan', '-help'],
      displayCommand: 'terraform plan -help',
      expect: /-detailed-exitcode/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'opentofu',
      storyIds: ['agentic-official-cli'],
      bin: 'tofu',
      argv: ['tofu', 'version'],
      displayCommand: 'tofu version',
      expect: /OpenTofu v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'plan-headless-help',
      productId: 'opentofu',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'tofu',
      argv: ['tofu', 'plan', '-help'],
      displayCommand: 'tofu plan -help',
      expect: /-detailed-exitcode/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'pulumi',
      storyIds: ['agentic-official-cli'],
      bin: 'pulumi',
      argv: ['pulumi', 'version'],
      displayCommand: 'pulumi version',
      expect: /v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'preview-json-help',
      productId: 'pulumi',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'pulumi',
      argv: ['pulumi', 'preview', '--help'],
      displayCommand: 'pulumi preview --help',
      expect: /--json/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'crossplane',
      storyIds: ['agentic-official-cli'],
      bin: 'crossplane',
      argv: ['crossplane', 'version', '--client'],
      displayCommand: 'crossplane version --client',
      expect: /Client Version: v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
]
