import type { LocalProbe } from './types'

export const probes: LocalProbe[] = [
    {
      probeId: 'cli-version',
      productId: 'terraform',
      storyIds: ['agentic-official-cli'],
      bin: 'terraform',
      argv: ['terraform', 'version'],
      displayCommand: 'terraform version',
      expect: /Terraform v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'plan-headless-help',
      productId: 'terraform',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'terraform',
      argv: ['terraform', 'plan', '-help'],
      displayCommand: 'terraform plan -help',
      expect: /-detailed-exitcode/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'opentofu',
      storyIds: ['agentic-official-cli'],
      bin: 'tofu',
      argv: ['tofu', 'version'],
      displayCommand: 'tofu version',
      expect: /OpenTofu v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'plan-headless-help',
      productId: 'opentofu',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'tofu',
      argv: ['tofu', 'plan', '-help'],
      displayCommand: 'tofu plan -help',
      expect: /-detailed-exitcode/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'pulumi',
      storyIds: ['agentic-official-cli'],
      bin: 'pulumi',
      argv: ['pulumi', 'version'],
      displayCommand: 'pulumi version',
      expect: /v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'preview-json-help',
      productId: 'pulumi',
      storyIds: ['agentic-headless', 'structured-plan-output'],
      bin: 'pulumi',
      argv: ['pulumi', 'preview', '--help'],
      displayCommand: 'pulumi preview --help',
      expect: /--json/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'crossplane',
      storyIds: ['agentic-official-cli'],
      bin: 'crossplane',
      argv: ['crossplane', 'version', '--client'],
      displayCommand: 'crossplane version --client',
      expect: /Client Version: v\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      // Honest negative: docs.crossplane.io/llms.txt redirects to the HTML docs shell
      // (/latest/) instead of serving an agent-readable index — a soft-404, recorded as such
      // (2026-09-23 depth spike).
      probeId: 'docs-llms-txt-soft404',
      productId: 'crossplane',
      storyIds: ['agentic-agent-docs'],
      bin: 'curl',
      argv: ['sh', '-c', 'curl -sL --max-time 20 https://docs.crossplane.io/llms.txt | head -c 15'],
      displayCommand: 'curl -sL https://docs.crossplane.io/llms.txt | head -c 15',
      expect: /<!doctype html/,
      timeoutMs: 30_000,
    },
    {
      // Honest negative: opentofu.org publishes no llms.txt (404) — recorded absence from the
      // 2026-09-23 depth spike.
      probeId: 'site-llms-txt-absent',
      productId: 'opentofu',
      storyIds: ['agentic-agent-docs'],
      bin: 'curl',
      argv: ['sh', '-c', 'curl -sL -o /dev/null -w "HTTP %{http_code}" --max-time 20 https://opentofu.org/llms.txt'],
      displayCommand: 'curl -sL -o /dev/null -w "HTTP %{http_code}" https://opentofu.org/llms.txt',
      expect: /HTTP 404/,
      timeoutMs: 30_000,
    },
]
