import { CURL_MCP_INIT, MCP_INITIALIZE, type LocalProbe } from './types'

  // Observability: grafana's official MCP server (brew-installed mcp-grafana) answers a stdio
  // initialize with serverInfo even with no Grafana configured — the handshake itself is the
  // keyless proof. The docker roundtrip is the arena's signature local proof: boot grafana-oss,
  // create a dashboard through the HTTP API (container-default admin:admin — local throwaway,
  // no cloud credentials), search it back, tear down. Hosted MCP endpoints (Sentry, Datadog,
  // New Relic, Honeycomb) are probed keylessly via their auth challenges / RFC 9728 metadata.
export const probes: LocalProbe[] = [
    {
      probeId: 'mcp-stdio-handshake',
      productId: 'grafana',
      storyIds: ['agentic-mcp-server', 'agent-queries-telemetry'],
      bin: 'mcp-grafana',
      argv: ['mcp-grafana'],
      displayCommand: `echo '<jsonrpc initialize>' | mcp-grafana`,
      stdinPayload: MCP_INITIALIZE,
      expect: /"serverInfo"/,
      longRunning: true,
      timeoutMs: 30_000,
    },
    {
      probeId: 'docker-provision-roundtrip',
      productId: 'grafana',
      storyIds: ['openness-self-host', 'dashboards-monitors-as-code', 'agentic-public-api'],
      bin: 'docker',
      argv: [
        'sh', '-c',
        'docker rm -f pa-grafana-probe >/dev/null 2>&1; docker run -d --name pa-grafana-probe -p 13000:3000 grafana/grafana-oss >/dev/null 2>&1; n=0; while [ $n -lt 45 ] && ! curl -s http://localhost:13000/api/health >/dev/null 2>&1; do sleep 2; n=$((n+1)); done; curl -s http://localhost:13000/api/health; echo; curl -s -X POST http://admin:admin@localhost:13000/api/dashboards/db -H "Content-Type: application/json" -d "{\\"dashboard\\":{\\"title\\":\\"PA Probe\\",\\"panels\\":[]},\\"overwrite\\":true}"; echo; curl -s "http://admin:admin@localhost:13000/api/search?query=PA%20Probe"; echo; docker rm -f pa-grafana-probe >/dev/null 2>&1',
      ],
      displayCommand: `docker run -d --name pa-grafana-probe -p 13000:3000 grafana/grafana-oss && curl localhost:13000/api/health && curl -X POST http://admin:admin@localhost:13000/api/dashboards/db -d '{"dashboard":{"title":"PA Probe"},"overwrite":true}' && curl 'http://admin:admin@localhost:13000/api/search?query=PA%20Probe'`,
      expect: /"title":"PA Probe"/,
      timeoutMs: 180_000,
    },
    {
      probeId: 'cli-version',
      productId: 'sentry',
      storyIds: ['agentic-official-cli'],
      bin: 'sentry-cli',
      argv: ['sentry-cli', '--version'],
      displayCommand: 'sentry-cli --version',
      expect: /sentry-cli \d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-remote-handshake',
      productId: 'sentry',
      storyIds: ['agentic-mcp-server'],
      bin: 'curl',
      argv: [
        'curl', '-s', '-i', '--max-time', '20', '-X', 'POST', 'https://mcp.sentry.dev/mcp',
        '-H', 'Content-Type: application/json',
        '-H', 'Accept: application/json, text/event-stream',
        '-d', CURL_MCP_INIT,
      ],
      displayCommand: `curl -si -X POST https://mcp.sentry.dev/mcp -H 'Content-Type: application/json' -d '<jsonrpc initialize>'`,
      expect: /oauth-protected-resource/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'datadog',
      storyIds: ['agentic-official-cli', 'agentic-headless'],
      bin: 'datadog-ci',
      argv: ['datadog-ci', 'version'],
      displayCommand: 'datadog-ci version',
      expect: /v\d+\.\d+\.\d+/,
      timeoutMs: 60_000,
    },
    {
      probeId: 'mcp-remote-handshake',
      productId: 'datadog',
      storyIds: ['agentic-mcp-server'],
      bin: 'curl',
      argv: [
        'curl', '-s', '-i', '--max-time', '20', '-X', 'POST', 'https://mcp.datadoghq.com/api/unstable/mcp-server/mcp',
        '-H', 'Content-Type: application/json',
        '-H', 'Accept: application/json, text/event-stream',
        '-d', CURL_MCP_INIT,
      ],
      displayCommand: `curl -si -X POST https://mcp.datadoghq.com/api/unstable/mcp-server/mcp -H 'Content-Type: application/json' -d '<jsonrpc initialize>'`,
      expect: /\{"errors":\["Unauthorized"\]\}/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'new-relic',
      storyIds: ['agentic-official-cli'],
      bin: 'newrelic',
      argv: ['newrelic', 'version'],
      displayCommand: 'newrelic version',
      expect: /newrelic version \d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-remote-handshake',
      productId: 'new-relic',
      storyIds: ['agentic-mcp-server'],
      bin: 'curl',
      argv: [
        'curl', '-s', '-i', '--max-time', '20', '-X', 'POST', 'https://mcp.newrelic.com/mcp',
        '-H', 'Content-Type: application/json',
        '-H', 'Accept: application/json, text/event-stream',
        '-d', CURL_MCP_INIT,
      ],
      displayCommand: `curl -si -X POST https://mcp.newrelic.com/mcp -H 'Content-Type: application/json' -d '<jsonrpc initialize>'`,
      expect: /"authentication_options"/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-remote-discovery',
      productId: 'honeycomb',
      storyIds: ['agentic-mcp-server'],
      bin: 'curl',
      argv: ['curl', '-s', '--max-time', '20', 'https://mcp.honeycomb.io/.well-known/oauth-protected-resource'],
      displayCommand: 'curl -s https://mcp.honeycomb.io/.well-known/oauth-protected-resource',
      expect: /"authorization_servers"/,
      timeoutMs: 30_000,
    },
]
