import { MCP_INITIALIZE, type LocalProbe } from './types'

export const probes: LocalProbe[] = [
    {
      probeId: 'cli-version',
      productId: 'trufflehog',
      storyIds: ['agentic-official-cli'],
      bin: 'trufflehog',
      argv: ['trufflehog', '--version'],
      displayCommand: 'trufflehog --version',
      expect: /trufflehog \d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'semgrep',
      storyIds: ['agentic-official-cli'],
      bin: 'semgrep',
      argv: ['semgrep', '--version'],
      displayCommand: 'semgrep --version',
      expect: /\d+\.\d+\.\d+/,
      timeoutMs: 60_000,
    },
    {
      probeId: 'cli-version',
      productId: 'gitleaks',
      storyIds: ['agentic-official-cli'],
      bin: 'gitleaks',
      argv: ['gitleaks', 'version'],
      displayCommand: 'gitleaks version',
      expect: /\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'snyk',
      storyIds: ['agentic-official-cli'],
      bin: 'snyk',
      argv: ['snyk', '--version'],
      displayCommand: 'snyk --version',
      expect: /\d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      probeId: 'mcp-stdio-handshake',
      productId: 'snyk',
      storyIds: ['agentic-mcp-server'],
      bin: 'snyk',
      argv: ['snyk', 'mcp', '-t', 'stdio'],
      displayCommand: `echo '<jsonrpc initialize>' | snyk mcp -t stdio`,
      stdinPayload: MCP_INITIALIZE,
      expect: /"serverInfo"/,
      longRunning: true,
      timeoutMs: 30_000,
    },
    {
      probeId: 'cli-version',
      productId: 'trivy',
      storyIds: ['agentic-official-cli'],
      bin: 'trivy',
      argv: ['trivy', '--version'],
      displayCommand: 'trivy --version',
      expect: /Version: \d+\.\d+\.\d+/,
      timeoutMs: 30_000,
    },
    {
      // Requires the official MCP plugin (`trivy plugin install mcp`) on the recording
      // machine; without it the probe fails, which is itself a finding (docs/PROVE-IT.md).
      probeId: 'mcp-stdio-handshake',
      productId: 'trivy',
      storyIds: ['agentic-mcp-server'],
      bin: 'trivy',
      argv: ['trivy', 'mcp', '--transport', 'stdio'],
      displayCommand: `echo '<jsonrpc initialize>' | trivy mcp --transport stdio`,
      stdinPayload: MCP_INITIALIZE,
      expect: /"serverInfo"/,
      longRunning: true,
      timeoutMs: 30_000,
    },
]
