import json

PATH = 'data/product-families.json'
fams = json.load(open(PATH))
by_id = {f['id']: f for f in fams}

def sub(id, name, blurb, docsUrl, arenaRef=None, note=None, acquired=None):
    e = {"id": id, "name": name, "blurb": blurb, "docsUrl": docsUrl, "arenaRef": arenaRef}
    if note: e["note"] = note
    if acquired: e["acquired"] = acquired
    assert len(blurb) <= 300, (id, 'blurb', len(blurb))
    if note: assert len(note) <= 300, (id, 'note', len(note))
    if arenaRef is None: assert note, id
    return e

# ---------------- Anthropic ----------------
by_id['anthropic'].update({
  "tagline": "Anthropic's product surface mapped by what you can do with each line: six judged products from the assistant app to Claude Design, and honest not-yet-judged cards for the rest.",
  "subProducts": [
    sub("claude", "Claude",
        "Ask, research with citations, analyze files, and build artifacts in one assistant across web, desktop, and mobile — with memory, connectors, and voice that carry across every surface.",
        "https://support.claude.com/en/",
        {"arenaId": "ai-assistants", "productId": "claude"}),
    sub("claude-code", "Claude Code",
        "Ship code end-to-end from the terminal, IDE, web, or CI: explore a codebase, edit files, run commands, and open the PR — with subagents, skills, hooks, and MCP.",
        "https://docs.claude.com/en/docs/claude-code/overview",
        {"arenaId": "ai-coding", "productId": "claude-code"}),
    sub("claude-design", "Claude Design",
        "Turn a written brief into interactive prototypes, decks, and marketing collateral: apply your own design system, refine with inline comments and sliders, and hand off to Claude Code to ship. An Anthropic Labs beta.",
        "https://claude.com/product/design",
        {"arenaId": "design-tools", "productId": "claude-design"}),
    sub("cowork", "Claude Cowork",
        "Hand Claude a folder and an outcome: it works through files, browsing, and multi-step office tasks in parallel sessions you review — the Claude Code harness for non-coders.",
        "https://claude.com/product/cowork",
        None,
        "A surface of the Claude app subscription, not separately adopted — its delegate-whole-tasks capabilities are judged inside the claude entry's agents-tasks stories; a second row would double-list one product."),
    sub("agent-sdk", "Claude Agent SDK",
        "Build your own agents on the same harness as Claude Code: the agent loop, tools, hooks, MCP, and skills as TypeScript and Python libraries.",
        "https://code.claude.com/docs/en/agent-sdk/overview",
        {"arenaId": "agent-frameworks", "productId": "claude-agent-sdk"}),
    sub("skills", "Anthropic Skills",
        "Package instructions, scripts, and resources into SKILL.md folders that Claude loads on demand — portable across the app, Claude Code, Cowork, and the API.",
        "https://code.claude.com/docs/en/skills",
        {"arenaId": "agent-skills", "productId": "anthropic-skills"}),
    sub("claude-in-chrome", "Claude in Chrome",
        "Claude acts in your browser: navigate, fill forms, and run web tasks from a side panel with per-site permissions and action confirmations.",
        "https://claude.com/claude-in-chrome",
        None,
        "No browsers arena yet (roadmap: planned), and browser-agents ranks developer automation frameworks — judging a consumer extension there would be the wrong axis (same call as Perplexity Comet)."),
    sub("claude-tag", "@Claude (Slack & Teams)",
        "Tag @Claude in a Slack or Teams thread to summarize, answer with workspace context, run analysis, and carry out standing instructions.",
        "https://claude.com/product/tag",
        None,
        "A bot that lives inside team-chat products, not a chat platform — ranking it against Slack itself would be the wrong axis; the underlying assistant is judged as claude."),
    sub("claude-for-microsoft-365", "Claude for Microsoft 365",
        "Work inside Office: interrogate and update Excel models cell by cell, draft Word docs with tracked changes, build decks from your templates, and triage Outlook.",
        "https://claude.com/claude-for-microsoft-365",
        None,
        "An integration surface of the Claude subscription inside Microsoft's apps — no office-suite arena, and the underlying assistant is already judged as claude."),
    sub("claude-science", "Claude Science",
        "A workbench for scientists: query scientific databases, run reproducible analyses on managed compute, visualize proteins and genomic data, and draft the manuscript alongside.",
        "https://claude.com/product/claude-science",
        None,
        "Beta. ai-research-agents ranks literature-review agents (Elicit, Consensus, FutureHouse); a compute-and-analysis workbench is a neighboring but different job. Watchlist line."),
    sub("claude-security", "Claude Security",
        "Point it at a codebase to find vulnerabilities, adversarially validate which findings are real, and get patch suggestions your team reviews.",
        "https://claude.com/product/claude-security",
        None,
        "Enterprise public beta; security-scanners ranks GA scanners any developer can adopt today (Semgrep, Snyk, Trivy). Bring-up candidate once generally available."),
    sub("managed-agents", "Managed Agents",
        "Host agents on Anthropic-run infrastructure straight from the API: managed sandboxes, stateful sessions, and scheduled runs without operating your own harness.",
        "https://platform.claude.com/docs",
        None,
        "Beta surface of the developer platform; proprietary model platforms aren't an arena we rank yet (roadmap: frontier-model-apis)."),
    sub("developer-platform", "Claude Developer Platform",
        "The API platform: Messages API, tool use, code execution, files, and agent infrastructure for building on Claude.",
        "https://platform.claude.com/docs",
        None,
        "Proprietary model APIs are not an arena we rank — inference-providers ranks hosts of open models, a different job (roadmap: frontier-model-apis)."),
  ],
})

# ---------------- OpenAI ----------------
by_id['openai'].update({
  "tagline": "OpenAI's product surface mapped by capability: the judged four plus honest cards for images, Work, ChatKit, and the platform — and the lines that shut down, documented, not hidden.",
  "subProducts": [
    sub("chatgpt", "ChatGPT",
        "Ask, research the web, and delegate whole tasks that come back as reviewable docs, decks, sites, and spreadsheets — one app across web, desktop, and mobile with projects, memory, and scheduled automations.",
        "https://learn.chatgpt.com/docs/use-chatgpt.md",
        {"arenaId": "ai-assistants", "productId": "chatgpt"}),
    sub("chatgpt-work", "ChatGPT Work",
        "Define an outcome and ChatGPT plans the work, browses in a cloud browser, uses your files and plugins, and returns a finished deliverable you review.",
        "https://learn.chatgpt.com/docs/get-started-with-work",
        None,
        "A mode of ChatGPT (it replaced agent mode in July 2026), sold on the same plans — judged inside the chatgpt entry's long-running-work and agents stories; a second row would double-list one product."),
    sub("images", "Image generation (GPT-Image-2.5)",
        "Generate and edit images in conversation — text-to-image, precise edits from reference images — and the same capability via the API (GPT-Image-2.5 Sunburst and Flare).",
        "https://developers.openai.com/api/docs/guides/image-generation",
        None,
        "A capability of ChatGPT and the API, not a separately adopted product — and no image-generation arena exists yet (roadmap: planned). Its in-app stories are judged inside the chatgpt entry."),
    sub("codex", "Codex",
        "A coding agent that writes, tests, reviews, and ships code — CLI, IDE extension, cloud sandboxes, Slack/Linear/GitHub integrations, and Codex Remote from your phone.",
        "https://developers.openai.com/codex",
        {"arenaId": "ai-coding", "productId": "codex"}),
    sub("codex-security", "Codex Security",
        "Scan repositories for vulnerabilities from a plugin, CLI, SDK, or the cloud, with adversarially-checked findings your team triages.",
        "https://developers.openai.com/codex",
        None,
        "A Codex sibling launched September 2026; security-scanners ranks established GA scanners — bring-up candidate once it has a record beyond launch week."),
    sub("agents-sdk", "Agents SDK",
        "Build agent loops with handoffs, guardrails, and sessions in TypeScript or Python — the open framework track alongside the hosted Agents API.",
        "https://developers.openai.com/api/docs/guides/agents",
        {"arenaId": "agent-frameworks", "productId": "openai-agents"}),
    sub("codex-plugins", "Plugins",
        "Package skills, MCP servers, and UI into plugins that run in both ChatGPT and Codex, distributed through a reviewed public directory with checkout-based monetization.",
        "https://developers.openai.com/plugins",
        {"arenaId": "agent-skills", "productId": "codex-plugins"}),
    sub("chatkit", "ChatKit",
        "Embed a production chat UI over your own agent backend: a widget with streaming, attachments, and theming, shipped from npm.",
        "https://developers.openai.com/api/docs/guides/agents",
        None,
        "A developer component (beta API), not a product users adopt on its own; no embeddable-AI-UI arena exists."),
    sub("agents-api", "Agents API",
        "Run agents on OpenAI-hosted infrastructure — the managed Codex harness with sessions and sandboxes, callable from your backend.",
        "https://developers.openai.com/api/docs/guides/agents",
        None,
        "Beta hosted-agents surface of the API platform; proprietary model platforms aren't an arena we rank yet (roadmap: frontier-model-apis)."),
    sub("api-platform", "API Platform",
        "The developer platform: Responses API, Realtime voice with SIP calls, hosted tools, containers, and fine-tuning.",
        "https://developers.openai.com/api/docs",
        None,
        "Proprietary model APIs are not an arena we rank — inference-providers ranks hosts of open models, a different job (roadmap: frontier-model-apis)."),
  ],
})

# ---------------- Google ----------------
by_id['google'].update({
  "tagline": "Google's AI product surface mapped by capability — eight judged lines from the Gemini app to Antigravity and Gemini Notebook, plus honest cards for Flow, AI Studio, and Gemini in Chrome.",
  "subProducts": [
    sub("gemini", "Gemini",
        "Chat with grounded answers, generate and edit images (Nano Banana), run Deep Research, build docs and apps in Canvas, and schedule actions — across web, mobile, and desktop apps.",
        "https://support.google.com/gemini/answer/13275745?hl=en",
        {"arenaId": "ai-assistants", "productId": "gemini"}),
    sub("antigravity", "Antigravity",
        "Run and supervise fleets of coding agents from a command center, IDE, CLI, or SDK — parallel worktrees, browser-in-the-loop verification, artifact review, skills, and MCP.",
        "https://antigravity.google/docs/getting-started",
        {"arenaId": "ai-coding", "productId": "antigravity"}),
    sub("gemini-cli", "Gemini CLI",
        "Open-source terminal agent for querying and editing large codebases with Gemini. Consumer tiers moved to Antigravity CLI in June 2026; this remains the API-key and Code Assist path.",
        "https://geminicli.com",
        {"arenaId": "ai-coding", "productId": "gemini-cli"}),
    sub("notebooklm", "Gemini Notebook (NotebookLM)",
        "Upload your own sources — PDFs, Docs, audio, YouTube — and get answers grounded only in them with citations, then turn them into reports, mind maps, slide decks, flashcards, and Audio or Video Overviews.",
        "https://support.google.com/notebooklm",
        {"arenaId": "ai-research-agents", "productId": "notebooklm"}),
    sub("jules", "Jules",
        "Assign a GitHub issue and get a reviewed plan, diff, and pull request back — an asynchronous coding agent on cloud VMs with a REST API and CLI.",
        "https://jules.google/docs",
        {"arenaId": "software-factory", "productId": "jules"}),
    sub("adk", "Agent Development Kit",
        "Build, evaluate, and deploy multi-agent systems in Python, TypeScript, Go, Java, or Kotlin, and ship them to Cloud Run or the Agent Platform.",
        "https://adk.dev",
        {"arenaId": "agent-frameworks", "productId": "google-adk"}),
    sub("ai-studio", "Google AI Studio",
        "Prototype with Gemini models, generate media, grab an API key, and vibe-code deployable apps in the browser — free.",
        "https://ai.google.dev/aistudio",
        None,
        "The developer console for the Gemini API; its app-building surface sits behind login, and vibe-coding ranks products whose whole job is prompt-to-app (Lovable, Bolt, v0). Watchlist for a Build-mode bring-up."),
    sub("flow", "Flow",
        "Make cinematic AI video and images with scene-level control and reusable ingredients — the creative studio that absorbed Whisk and ImageFX, running Veo and Gemini Omni.",
        "https://flow.google.com",
        None,
        "No image/video-generation arena exists yet (roadmap: image-generation planned) — nothing honest to rank it against."),
    sub("gemini-in-chrome", "Gemini in Chrome",
        "Summarize and compare across open tabs, ask about the page you are on, and let auto-browse finish tasks in the browser.",
        "https://gemini.google/overview/gemini-in-chrome/",
        None,
        "A paid-tier feature of Chrome and the Gemini subscription, not a separately adopted product; the browsers arena is planned, not live."),
    sub("gemini-code-assist", "Gemini Code Assist",
        "In-IDE completion, chat, and agentic multi-step edits for Google Cloud organizations under enterprise compliance controls.",
        "https://docs.cloud.google.com/gemini/docs/codeassist/overview",
        None,
        "Individual tiers ended June 2026 (migrated to Antigravity); what remains is an enterprise SKU of capability already judged via Antigravity and Gemini CLI."),
    sub("firebase", "Firebase",
        "App-development backend platform: auth, databases, hosting, and functions.",
        "https://firebase.google.com/docs?hl=en",
        {"arenaId": "backend-as-a-service", "productId": "firebase"}),
    sub("angular", "Angular",
        "Google's TypeScript web application framework.",
        "https://angular.dev",
        {"arenaId": "frontend-frameworks", "productId": "angular"}),
  ],
})

# ---------------- xAI (new) ----------------
assert 'xai' not in by_id
fams.append({
  "id": "xai",
  "name": "xAI",
  "vendor": "xAI (SpaceXAI)",
  "tagline": "xAI's product surface — Grok judged among the AI assistants, with honest cards for Grok Build, Grok Bot, Imagine, Grokipedia, and the API.",
  "parent": {"arenaId": "ai-assistants", "productId": "grok"},
  "subProducts": [
    sub("grok", "Grok",
        "Chat by text or voice, analyze files, generate images and video with Imagine, and connect Gmail, Drive, Teams, Salesforce, and custom MCP tools — on the web, iOS, Android, and inside X.",
        "https://docs.x.ai/grok/overview.md",
        {"arenaId": "ai-assistants", "productId": "grok"}),
    sub("grok-build", "Grok Build",
        "A terminal coding agent: explore, edit, and run code with plan mode, subagents, worktrees, skills and plugin marketplaces, MCP, and headless scripting — installed with one curl.",
        "https://docs.x.ai/build/overview.md",
        None,
        "Beta (May 2026) and shipping weekly; a genuine ai-coding contestant queued as a first-priority bring-up candidate for the next wave — deferred, not excluded."),
    sub("grok-bot", "Grok Bot",
        "Named, persistent AI teammates on cloud computers — browser, filesystem, terminal — that take multi-step tasks, learn skills by demonstration, and run scheduled routines; bundled with Cursor plans.",
        "https://docs.x.ai/grok-bot/overview.md",
        None,
        "GA August 2026, but a computer-use-teammate category with no arena yet; judging it in browser-agents or software-factory would misstate its job."),
    sub("grok-imagine", "Grok Imagine",
        "Generate and edit images and video — multi-image editing, image-to-video, cinematic aspect ratios — inside the Grok app and via the Imagine API.",
        "https://docs.x.ai/developers/model-capabilities/imagine.md",
        None,
        "A capability of Grok and the API, not a standalone app; no image-generation arena exists yet (roadmap: planned)."),
    sub("grokipedia", "Grokipedia",
        "Browse and search an AI-written and AI-maintained encyclopedia.",
        "https://grokipedia.com",
        None,
        "A content destination, not a tool with user stories we rank — no encyclopedia or reference arena."),
    sub("xai-api", "xAI API",
        "Build on Grok models with one key: text and reasoning, image and video generation, speech-to-speech phone agents over SIP, RAG collections, and server-side tools.",
        "https://docs.x.ai",
        None,
        "Proprietary model APIs are not an arena we rank yet (roadmap: frontier-model-apis) — inference-providers ranks hosts of open models, a different job."),
  ],
})

json.dump(fams, open(PATH, 'w'), indent=2)
print('families:', [f['id'] for f in fams])
for fid in ('anthropic', 'openai', 'google', 'xai'):
    f = by_id.get(fid) or [x for x in fams if x['id'] == fid][0]
    judged = [s['id'] for s in f['subProducts'] if s['arenaRef']]
    pageonly = [s['id'] for s in f['subProducts'] if not s['arenaRef']]
    print(fid, 'judged:', judged, '| page-only:', pageonly)
