#!/bin/sh
# Live-verify every candidate corpus URL before it is written into products.json.
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0 Safari/537.36"
while IFS= read -r u; do
  [ -z "$u" ] && continue
  code=$(curl -s -o /dev/null -w "%{http_code}" -L --max-time 20 -A "$UA" "$u")
  echo "$code $u"
done <<'EOF'
https://resend.com/docs/introduction.md
https://resend.com/docs/api-reference/introduction.md
https://resend.com/docs/api-reference/emails/send-email.md
https://resend.com/docs/api-reference/emails/send-batch-emails.md
https://resend.com/docs/api-reference/emails/list-received-emails.md
https://resend.com/docs/api-reference/domains/create-domain.md
https://resend.com/docs/api-reference/domains/verify-domain.md
https://resend.com/docs/api-reference/webhooks/create-webhook.md
https://resend.com/docs/api-reference/suppressions/add-suppression.md
https://resend.com/docs/api-reference/api-keys/create-api-key.md
https://resend.com/docs/api-reference/broadcasts/send-broadcast.md
https://resend.com/docs/add-a-domain.md
https://resend.com/docs/send-with-smtp.md
https://resend.com/docs/dashboard/emails/idempotency-keys.md
https://postmarkapp.com/developer/api/overview
https://postmarkapp.com/developer/api/email-api
https://postmarkapp.com/developer/api/templates-api
https://postmarkapp.com/developer/api/bounce-api
https://postmarkapp.com/developer/api/messages-api
https://postmarkapp.com/developer/api/domains-api
https://postmarkapp.com/developer/api/servers-api
https://postmarkapp.com/developer/api/stats-api
https://postmarkapp.com/developer/webhooks/webhooks-overview
https://postmarkapp.com/developer/user-guide/send-email-with-api
https://postmarkapp.com/developer/integration/official-libraries
https://postmarkapp.com/developer/user-guide/inbound
https://postmarkapp.com/why/deliverability
https://postmarkapp.com/pricing
https://documentation.mailgun.com/docs/mailgun/get-started.md
https://documentation.mailgun.com/docs/mailgun/quickstart.md
https://documentation.mailgun.com/docs/mailgun/mcp.md
https://documentation.mailgun.com/docs/mailgun/api-reference/api-overview.md
https://documentation.mailgun.com/docs/mailgun/api-reference/send/mailgun.md
https://documentation.mailgun.com/docs/mailgun/api-reference/mg-auth.md
https://documentation.mailgun.com/docs/mailgun/api-reference/analytics/mg-webhooks.md
https://documentation.mailgun.com/docs/mailgun/api-reference/developer-tools.md
https://documentation.mailgun.com/docs/mailgun/email-best-practices/dns.md
https://documentation.mailgun.com/docs/mailgun/email-best-practices/best_practices.md
https://documentation.mailgun.com/docs/mailgun/sdk/introduction.md
https://documentation.mailgun.com/docs/inboxready/intro-ir.md
https://documentation.mailgun.com/docs/inboxready/inbox-placement-ir.md
https://documentation.mailgun.com/docs/mailgun/faq/sending.md
https://documentation.mailgun.com/docs/mailgun/faq/receiving.md
https://www.mailgun.com/pricing/
https://www.twilio.com/docs/sendgrid
https://www.twilio.com/docs/sendgrid/for-developers/sending-email/sandbox-mode
https://www.twilio.com/docs/sendgrid/for-developers/tracking-events/getting-started-event-webhook
https://www.twilio.com/docs/sendgrid/for-developers/parsing-email/setting-up-the-inbound-parse-webhook
https://www.twilio.com/docs/sendgrid/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates
https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send
https://www.twilio.com/docs/sendgrid/for-developers/sending-email/getting-started-smtp
https://sendgrid.com/en-us/pricing
https://sendgrid.com/en-us/solutions/email-api
https://www.twilio.com/docs/sendgrid/ui/analytics-and-reporting/deliverability-insights
https://www.twilio.com/docs/sendgrid/for-developers/sending-email/dedicated-ip-addresses
https://docs.aws.amazon.com/ses/latest/dg/setting-up.html
https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication.html
https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html
https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html
https://docs.aws.amazon.com/ses/latest/dg/monitor-sending-activity.html
https://docs.aws.amazon.com/ses/latest/dg/send-email-smtp.html
https://docs.aws.amazon.com/ses/latest/dg/dedicated-ip.html
https://docs.aws.amazon.com/ses/latest/dg/monitor-using-event-publishing.html
https://docs.aws.amazon.com/ses/latest/dg/receiving-email.html
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html
https://aws.amazon.com/ses/pricing/
https://aws.amazon.com/ses/faqs/
https://docs.usestable.com/docs/getting-started.md
https://docs.usestable.com/docs/webhooks.md
https://docs.usestable.com/docs/the-mail-item-object.md
https://docs.usestable.com/docs/checks.md
https://docs.usestable.com/docs/the-location-object.md
https://docs.usestable.com/docs/create-a-registered-agent-location.md
https://docs.usestable.com/docs/companies.md
https://docs.usestable.com/llms.txt
https://www.usestable.com/products/registered-agent
https://www.usestable.com/security
https://www.usestable.com/about
https://www.virtualpostmail.com/virtual-mailbox/
https://www.virtualpostmail.com/virtual-mailbox/check-deposit/
https://www.virtualpostmail.com/registered-agent/
https://www.virtualpostmail.com/pricing/
https://www.virtualpostmail.com/developers/
https://www.virtualpostmail.com/security/
https://www.virtualpostmail.com/trulease/
https://www.virtualpostmail.com/truresidence/
https://www.virtualpostmail.com/trustart/
https://www.virtualpostmail.com/addresses/overview/
https://www.virtualpostmail.com/proof-of-address/
https://www.earthclassmail.com/
https://www.legalzoom.com/business/business-operations/lz-virtual-mail-overview.html
https://www.legalzoom.com/virtual-mail/addresses.html
https://www.anytimemailbox.com/
https://www.anytimemailbox.com/how-it-works
https://www.anytimemailbox.com/mail-forwarding
https://www.anytimemailbox.com/mail-center
https://www.anytimemailbox.com/mail-center/faq
https://www.anytimemailbox.com/locations
https://www.anytimemailbox.com/business-owners
https://www.anytimemailbox.com/digital-mail/case-studies
https://developers.google.com/gmail/api/guides
https://developers.google.com/gmail/api/reference/rest
https://developers.google.com/gmail/api/reference/rest/v1/users.messages/send
https://developers.google.com/gmail/api/guides/push
https://developers.google.com/gmail/api/guides/sending
https://developers.google.com/gmail/api/auth/scopes
https://developers.google.com/gmail/imap/imap-smtp
https://developers.google.com/workspace/add-ons/gmail
https://workspace.google.com/products/gmail/
https://workspace.google.com/pricing
https://support.google.com/mail/answer/7190
https://support.google.com/mail/answer/7622010
https://support.google.com/mail/answer/9214602
https://support.google.com/mail/answer/1306849
https://support.google.com/mail/answer/3341840
https://support.google.com/mail/answer/2819488
https://support.google.com/mail/answer/138350
https://support.google.com/mail/answer/7126229
https://support.google.com/mail/answer/14199860
https://mail.google.com/
https://www.google.com/gmail/about/
EOF
