#!/usr/bin/env python3
# Writes data/frontier-models/products.json. Every URL in here was live-verified (see
# .pa-tmp/verify-fm-urls.sh run log) before commit. Jev's corpus is deep by design (founder
# emphasis): all of docs.typesafe.ai's llms.txt-indexed .md mirrors minus the granular JS API
# class pages, the typesafe.ai site pages, the awesome-jev community list, TypeSafe's own
# GitHub repos (skills, SDK adapters), and the third-party Open-Jev HF replicas — the replicas
# are ecosystem signal, NOT TypeSafe products, and are attributed as such in evidence.
import json, os

TS_DOCS = [
    "agent-skill", "api", "concepts/how-to-build-with-system-one", "concepts/state",
    "concepts/system-one", "concepts/use-case-map", "confidence", "cookbooks",
    "cookbooks/autoformat", "cookbooks/autoresearch_feature_discovery", "cookbooks/citation_check",
    "cookbooks/classification_using_confidence", "cookbooks/classifying_rag_passages",
    "cookbooks/consistency_choice_cookbook", "cookbooks/consistency_noul_cookbook",
    "cookbooks/date_extraction_cookbook", "cookbooks/entity_alignment", "cookbooks/function_calling",
    "cookbooks/hierarchical_classification", "cookbooks/llm_guardrails", "cookbooks/parallel_questions",
    "cookbooks/pre_parsed_value_extraction_cookbook", "cookbooks/rerank_typesafe",
    "cookbooks/sde_cascade", "cookbooks/semantic_find", "cookbooks/skill_suggestion",
    "demos", "demos/smart-home", "introduction/coding-agents",
    "introduction/machine-learning-primer", "introduction/quickstart", "legal",
    "model-jaggedness/jev-1.13", "models", "patterns", "patterns/composite-scoring",
    "patterns/confidence-routing", "patterns/fan-out", "patterns/intent-routing",
    "primitives", "primitives/advanced", "primitives/choice", "primitives/noul",
    "primitives/score", "sdk", "sdk/javascript", "sdk/javascript/api",
    "sdk/javascript/changelog", "sdk/python", "sdk/python/api", "sdk/python/api/clients/async",
    "sdk/python/api/clients/sync", "sdk/python/api/retries", "sdk/python/api/types/questions",
    "sdk/python/api/types/responses", "sdk/python/changelog", "sdk/python/usage",
]

products = [
    {
        "id": "jev",
        "name": "Jev (TypeSafe AI)",
        "vendor": "TypeSafe AI",
        "type": "commercial",
        "urls": {
            "site": "https://typesafe.ai",
            "docs": "https://docs.typesafe.ai/introduction.md",
            "changelog": "https://docs.typesafe.ai/sdk/python/changelog.md",
            "github": "https://github.com/typesafe-ai/typesafe-sdk-python",
            "extra": [
                "https://docs.typesafe.ai/llms.txt",
                *[f"https://docs.typesafe.ai/{p}.md" for p in TS_DOCS],
                "https://typesafe.ai/blog/introducing-system-one-models-and-jev",
                "https://typesafe.ai/blog/antibenchmaxxing",
                "https://typesafe.ai/blog/bitterest-lesson",
                "https://typesafe.ai/manifesto",
                "https://typesafe.ai/team",
                "https://typesafe.ai/legal/privacy-policy",
                "https://typesafe.ai/legal/terms",
                "https://typesafe.ai/legal/data-processing",
                "https://raw.githubusercontent.com/typesafe-ai/skills/HEAD/README.md",
                "https://raw.githubusercontent.com/typesafe-ai/typesafe-sdk-js/HEAD/README.md",
                "https://raw.githubusercontent.com/typesafe-ai/system-one-adapter-python/HEAD/README.md",
                "https://raw.githubusercontent.com/yibie/awesome-jev/main/README.md",
                "https://huggingface.co/ZefanCai/Open-Jev-9B",
                "https://huggingface.co/ZefanCai/Open-Jev-2B",
            ],
        },
        "links": {
            "api": "https://docs.typesafe.ai/api",
            "app": "https://typesafe.ai",
        },
        "businessModel": {
            "models": ["usage-based", "enterprise-custom"],
            "summary": "Usage-based API: $0.042 per million input tokens (output tokens free), early access with dynamic rate limits; custom and enterprise plans with higher limits via sales.",
            "url": "https://docs.typesafe.ai/models",
        },
        "install": [
            {"label": "pip", "command": "pip install typesafe-sdk", "url": "https://docs.typesafe.ai/sdk/python"},
            {"label": "npm", "command": "npm install @typesafe-ai/sdk", "url": "https://docs.typesafe.ai/sdk/javascript"},
        ],
    },
    {
        "id": "claude",
        "name": "Claude (models & API)",
        "vendor": "Anthropic",
        "type": "commercial",
        "urls": {
            "site": "https://www.anthropic.com",
            "docs": "https://platform.claude.com/docs/en/intro.md",
            "changelog": "https://platform.claude.com/docs/en/release-notes/api.md",
            "github": "https://github.com/anthropics/anthropic-sdk-python",
            "extra": [
                "https://docs.claude.com/llms.txt",
                "https://platform.claude.com/docs/en/about-claude/models/overview.md",
                "https://platform.claude.com/docs/en/about-claude/models/model-ids-and-versions.md",
                "https://platform.claude.com/docs/en/about-claude/models/choosing-a-model.md",
                "https://platform.claude.com/docs/en/about-claude/pricing.md",
                "https://platform.claude.com/docs/en/about-claude/model-deprecations.md",
                "https://platform.claude.com/docs/en/api/overview.md",
                "https://platform.claude.com/docs/en/api/rate-limits.md",
                "https://platform.claude.com/docs/en/api/versioning.md",
                "https://platform.claude.com/docs/en/api/service-tiers.md",
                "https://platform.claude.com/docs/en/build-with-claude/overview.md",
                "https://platform.claude.com/docs/en/build-with-claude/context-windows.md",
                "https://platform.claude.com/docs/en/build-with-claude/prompt-caching.md",
                "https://platform.claude.com/docs/en/build-with-claude/batch-processing.md",
                "https://platform.claude.com/docs/en/build-with-claude/streaming.md",
                "https://platform.claude.com/docs/en/build-with-claude/structured-outputs.md",
                "https://platform.claude.com/docs/en/build-with-claude/extended-thinking.md",
                "https://platform.claude.com/docs/en/agents-and-tools/tool-use/overview.md",
                "https://platform.claude.com/docs/en/agents-and-tools/tool-use/parallel-tool-use.md",
                "https://platform.claude.com/docs/en/agents-and-tools/mcp-connector.md",
                "https://platform.claude.com/docs/en/agents-and-tools/agent-skills/overview.md",
                "https://platform.claude.com/docs/en/cli-sdks-libraries/overview.md",
                "https://platform.claude.com/docs/en/manage-claude/admin-api.md",
                "https://platform.claude.com/docs/en/manage-claude/usage-cost-api.md",
                "https://www.anthropic.com/pricing",
                "https://www.anthropic.com/claude",
                "https://www.anthropic.com/transparency",
            ],
        },
        "links": {
            "app": "https://platform.claude.com",
            "api": "https://platform.claude.com/docs/en/api/overview",
            "mcp": "https://platform.claude.com/docs/en/agents-and-tools/mcp-connector",
        },
        "businessModel": {
            "models": ["usage-based", "enterprise-custom"],
            "summary": "Usage-based per-token API pricing published per model, with batch and prompt-caching discounts, priority service tiers, and enterprise agreements.",
            "url": "https://platform.claude.com/docs/en/about-claude/pricing",
        },
        "install": [
            {"label": "pip", "command": "pip install anthropic", "url": "https://platform.claude.com/docs/en/cli-sdks-libraries/overview"},
            {"label": "npm", "command": "npm install @anthropic-ai/sdk", "url": "https://platform.claude.com/docs/en/cli-sdks-libraries/overview"},
        ],
    },
    {
        "id": "gpt",
        "name": "GPT (OpenAI API)",
        "vendor": "OpenAI",
        "type": "commercial",
        "urls": {
            "site": "https://developers.openai.com",
            "docs": "https://developers.openai.com/api/docs/quickstart.md",
            "changelog": "https://developers.openai.com/api/docs/changelog.md",
            "github": "https://github.com/openai/openai-python",
            "extra": [
                "https://developers.openai.com/llms.txt",
                "https://developers.openai.com/api/llms.txt",
                "https://developers.openai.com/api/docs/models.md",
                "https://developers.openai.com/api/docs/models/compare.md",
                "https://developers.openai.com/api/docs/pricing.md",
                "https://developers.openai.com/api/docs/deprecations.md",
                "https://developers.openai.com/api/docs/guides/rate-limits.md",
                "https://developers.openai.com/api/docs/guides/function-calling.md",
                "https://developers.openai.com/api/docs/guides/structured-outputs.md",
                "https://developers.openai.com/api/docs/guides/streaming-responses.md",
                "https://developers.openai.com/api/docs/guides/prompt-caching.md",
                "https://developers.openai.com/api/docs/guides/batch.md",
                "https://developers.openai.com/api/docs/guides/evals.md",
                "https://developers.openai.com/api/docs/guides/supervised-fine-tuning.md",
                "https://developers.openai.com/api/docs/guides/reinforcement-fine-tuning.md",
                "https://developers.openai.com/api/docs/guides/safety-best-practices.md",
                "https://developers.openai.com/api/docs/guides/tools.md",
                "https://developers.openai.com/api/docs/guides/text.md",
                "https://developers.openai.com/api/docs/guides/migrate-to-responses.md",
                "https://developers.openai.com/api/docs/libraries.md",
                "https://developers.openai.com/api/docs/guides/agents.md",
                "https://developers.openai.com/cookbook/llms.txt",
            ],
        },
        "links": {
            "app": "https://platform.openai.com",
            "api": "https://developers.openai.com/api/reference",
        },
        "businessModel": {
            "models": ["usage-based", "enterprise-custom"],
            "summary": "Usage-based per-token API pricing published per model, with batch discounts, cached-input pricing, fine-tuning surcharges, and enterprise/scale tiers.",
            "url": "https://developers.openai.com/api/docs/pricing",
        },
        "install": [
            {"label": "pip", "command": "pip install openai", "url": "https://developers.openai.com/api/docs/libraries"},
            {"label": "npm", "command": "npm install openai", "url": "https://developers.openai.com/api/docs/libraries"},
        ],
    },
    {
        "id": "gemini",
        "name": "Gemini (API)",
        "vendor": "Google",
        "type": "commercial",
        "urls": {
            "site": "https://ai.google.dev",
            "docs": "https://ai.google.dev/gemini-api/docs",
            "changelog": "https://ai.google.dev/gemini-api/docs/changelog",
            "github": "https://github.com/googleapis/python-genai",
            "extra": [
                "https://ai.google.dev/gemini-api/docs/models",
                "https://ai.google.dev/gemini-api/docs/pricing",
                "https://ai.google.dev/gemini-api/docs/rate-limits",
                "https://ai.google.dev/gemini-api/docs/quickstart",
                "https://ai.google.dev/gemini-api/docs/function-calling",
                "https://ai.google.dev/gemini-api/docs/structured-output",
                "https://ai.google.dev/gemini-api/docs/thinking",
                "https://ai.google.dev/gemini-api/docs/caching",
                "https://ai.google.dev/gemini-api/docs/batch-api",
                "https://ai.google.dev/gemini-api/docs/openai",
                "https://ai.google.dev/gemini-api/docs/deprecations",
                "https://ai.google.dev/gemini-api/docs/libraries",
                "https://ai.google.dev/gemini-api/docs/safety-settings",
                "https://ai.google.dev/gemini-api/docs/model-tuning",
                "https://ai.google.dev/gemini-api/docs/embeddings",
                "https://ai.google.dev/gemini-api/docs/live",
                "https://ai.google.dev/gemini-api/terms",
            ],
        },
        "links": {
            "app": "https://aistudio.google.com",
            "api": "https://ai.google.dev/api",
        },
        "businessModel": {
            "models": ["free-tier", "usage-based", "enterprise-custom"],
            "summary": "Free tier in AI Studio plus usage-based per-token paid tier with published per-model prices; enterprise consumption via Vertex AI.",
            "url": "https://ai.google.dev/gemini-api/docs/pricing",
        },
        "install": [
            {"label": "pip", "command": "pip install google-genai", "url": "https://ai.google.dev/gemini-api/docs/libraries"},
            {"label": "npm", "command": "npm install @google/genai", "url": "https://ai.google.dev/gemini-api/docs/libraries"},
        ],
    },
    {
        "id": "llama",
        "name": "Llama",
        "vendor": "Meta",
        "type": "commercial",
        "urls": {
            "site": "https://www.llama.com",
            "docs": "https://www.llama.com/docs/overview/",
            "github": "https://github.com/meta-llama/llama-models",
            "extra": [
                "https://www.llama.com/docs/get-started/",
                "https://www.llama.com/docs/model-cards-and-prompt-formats/",
                "https://www.llama.com/docs/llama-everywhere/",
                "https://www.llama.com/llama-downloads/",
                "https://www.llama.com/faq/",
                "https://llama.developer.meta.com",
                "https://huggingface.co/meta-llama",
                "https://raw.githubusercontent.com/meta-llama/llama-models/HEAD/README.md",
            ],
        },
        "links": {
            "app": "https://llama.developer.meta.com",
        },
        "businessModel": {
            "models": ["open-weights", "usage-based"],
            "summary": "Open-weight models free to download and self-host under the Llama Community License; Meta's hosted Llama API adds usage-based hosted access.",
            "url": "https://www.llama.com/llama-downloads/",
        },
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "vendor": "DeepSeek",
        "type": "commercial",
        "urls": {
            "site": "https://www.deepseek.com",
            "docs": "https://api-docs.deepseek.com",
            "changelog": "https://api-docs.deepseek.com/updates",
            "github": "https://github.com/deepseek-ai/DeepSeek-V3",
            "extra": [
                "https://api-docs.deepseek.com/quick_start/pricing",
                "https://api-docs.deepseek.com/quick_start/rate_limit",
                "https://api-docs.deepseek.com/quick_start/error_codes",
                "https://api-docs.deepseek.com/guides/function_calling",
                "https://api-docs.deepseek.com/guides/json_mode",
                "https://api-docs.deepseek.com/guides/kv_cache",
                "https://api-docs.deepseek.com/guides/reasoning_model",
                "https://api-docs.deepseek.com/api/deepseek-api",
                "https://huggingface.co/deepseek-ai",
            ],
        },
        "links": {
            "app": "https://platform.deepseek.com",
            "api": "https://api-docs.deepseek.com/api/deepseek-api",
        },
        "businessModel": {
            "models": ["open-weights", "usage-based"],
            "summary": "Open-weight model releases on Hugging Face plus a low-cost usage-based API with published per-token pricing and off-peak/context-cache discounts.",
            "url": "https://api-docs.deepseek.com/quick_start/pricing",
        },
    },
    {
        "id": "mistral",
        "name": "Mistral",
        "vendor": "Mistral AI",
        "type": "commercial",
        "urls": {
            "site": "https://mistral.ai",
            "docs": "https://docs.mistral.ai",
            "changelog": "https://docs.mistral.ai/inference/model-lifecycle",
            "github": "https://github.com/mistralai/client-python",
            "extra": [
                "https://docs.mistral.ai/llms.txt",
                "https://docs.mistral.ai/getting-started/platform-overview",
                "https://docs.mistral.ai/getting-started/clients",
                "https://docs.mistral.ai/getting-started/quickstarts/developer/first-api-request",
                "https://docs.mistral.ai/getting-started/quickstarts/studio/activate-and-generate-api-key",
                "https://docs.mistral.ai/inference",
                "https://docs.mistral.ai/inference/priority-tier",
                "https://docs.mistral.ai/inference/regional-inference",
                "https://docs.mistral.ai/resources/known-limitations",
                "https://docs.mistral.ai/studio/conversations/function-calling",
                "https://docs.mistral.ai/studio/conversations/structured-output",
                "https://docs.mistral.ai/studio/conversations/structured-output/custom",
                "https://docs.mistral.ai/studio/conversations/reasoning",
                "https://docs.mistral.ai/studio/conversations/moderation",
                "https://docs.mistral.ai/studio/conversations/advanced/prompt-caching",
                "https://docs.mistral.ai/studio/conversations/advanced/predicted-outputs",
                "https://docs.mistral.ai/studio/batch-processing",
                "https://docs.mistral.ai/api/endpoint/models",
                "https://docs.mistral.ai/admin/billing-usage/usage-limits",
                "https://mistral.ai/pricing",
                "https://mistral.ai/models",
                "https://huggingface.co/mistralai",
            ],
        },
        "links": {
            "app": "https://console.mistral.ai",
            "api": "https://docs.mistral.ai/api",
        },
        "businessModel": {
            "models": ["free-tier", "usage-based", "open-weights", "enterprise-custom"],
            "summary": "La Plateforme offers a free tier and usage-based per-token pricing; many models also ship as downloadable open weights (Apache 2.0 or MRL licenses).",
            "url": "https://mistral.ai/pricing",
        },
        "install": [
            {"label": "pip", "command": "pip install mistralai", "url": "https://docs.mistral.ai/getting-started/clients"},
            {"label": "npm", "command": "npm install @mistralai/mistralai", "url": "https://docs.mistral.ai/getting-started/clients"},
        ],
    },
]

os.makedirs('data/frontier-models', exist_ok=True)
with open('data/frontier-models/products.json', 'w') as f:
    json.dump(products, f, indent=2, ensure_ascii=False)
    f.write('\n')
print(f"wrote {len(products)} products; url counts:")
for p in products:
    n = 3 + len(p['urls'].get('extra', []))
    print(' ', p['id'], n)
